#!/usr/bin/python

Import('env', 'InstallDir')

t = env.Install('$OUT_DIR', env.Program('PerformanceTests', Glob('*.cpp')))
PerformanceTests = InstallDir(env, '$OUT_DIR/SoarPerformanceTests/', 'TestAgents')

env.Alias('performance_tests', t + PerformanceTests)
