#!/usr/bin/python

import glob
import sys

Import('env')
env = env.Clone()
env.Prepend(CPPPATH = ['src', 
		       'include', 
		       '../SoarKernel/include',
		       '../CLI/include',
		       '../ElementXML/include',
		       '../ConnectionSML/include'])

libadd = [
	   'ElementXML',
	   'CommandLineInterface',
	   'ConnectionSML',
	   'SoarKernel',
	   ]

libpath = [ 
	    '../SoarKernel',
	    '../CLI',
	    '../ConnectionSML',
	    '../ElementXML', 
	    '../pcre', 
	    ]

if env['scu']:
	SoarKernelSML = env.SharedLibrary('SoarKernelSML', 'KernelSML.cxx', LIBS = libadd, LIBPATH = libpath)
else:
	SoarKernelSML = env.SharedLibrary('SoarKernelSML', glob.glob('src/*.cpp'), LIBS = libadd, LIBPATH = libpath)
env.Install('#SoarLibrary/lib', SoarKernelSML)

