#!/usr/bin/python

import glob
import sys
import os

Import('env')
env = env.Clone()
env.Prepend(CPPPATH = ['src', 
		       'include', 
		       '../SoarKernel/include',
		       '../CLI/include',
		       '../ElementXML/include',
		       '../ConnectionSML/include'])

if sys.platform == 'cygwin':
	env.Append(CPPFLAGS = ' -D_USRDLL')
	env['no_import_lib'] = 1

libadd = [
	   'ElementXML',
	   'ConnectionSML',
	   'CommandLineInterface',
	   'SoarKernel',
	   ]

if sys.platform == 'cygwin':
	   libadd.extend(['pcre',])

if sys.platform == 'cygwin':
	libadd.extend(['ws2_32',])
	 
libpath = [ 
	    '../SoarKernel',
	    '../CLI',
	    '../ConnectionSML',
	    '../ElementXML', 
	    '../pcre', 
	    '../../SoarLibrary/lib',
	    ]

if env['scu']:
	SoarKernelSML = env.SharedLibrary('SoarKernelSML', ['KernelSML.cxx', '../SoarKernel/sqlite3.os'], LIBS = libadd, LIBPATH = libpath)
else:
	SoarKernelSML = env.SharedLibrary('SoarKernelSML', [glob.glob('src/*.cpp'), '../SoarKernel/sqlite3.os'], LIBS = libadd, LIBPATH = libpath)
env.Install('#SoarLibrary/lib', SoarKernelSML)

