#!/usr/bin/python

Import('env')
env = env.Clone()
env.Prepend(CPPPATH = ['#ClientSML/src', '#ElementXML/src', '#ConnectionSML/src'])

libadd = ['ClientSML', 'ConnectionSML', 'ElementXML']

env.Append(LIBS = libadd, LIBPATH = '$PREFIX/lib')
TestSMLEvents = env.Program('TestSMLEvents', Glob('*.cpp'))
env.Install('$PREFIX/bin', TestSMLEvents)

