/* DO NOT EDIT THIS FILE - it is machine generated */
/* Generated for class threepenny.ThreePennyNativeTest */
/* Generated from ThreePennyNativeTest.java*/

#ifndef _Included_threepenny_ThreePennyNativeTest
#define _Included_threepenny_ThreePennyNativeTest
#include <jni.h>
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     threepenny_ThreePennyNativeTest
 * Method:    jniDoNativeTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_threepenny_ThreePennyNativeTest_jniDoNativeTest
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
