#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#

Import('compEnv')
env = compEnv.Clone()

TestSMLPerformance = env.Program('TestSMLPerformance', Glob('*.cpp'))
Install('$PREFIX/bin', TestSMLPerformance)

