#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
Import('compEnv')
TestSMLPerformance = compEnv.Program('TestSMLPerformance', Glob('*.cpp'))
compEnv.Install('$PREFIX/bin', TestSMLPerformance)

