#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
Import('env')
TestSMLPerformance = env.Program('TestSMLPerformance', Glob('*.cpp'))
env.Alias('TestSMLPerformance', env.Install('$OUT_DIR', TestSMLPerformance))

