#!/usr/bin/python

Import('env')
env = env.Clone()

env.Prepend(CPPPATH = ['src', 'include', '#ElementXML/include',])

if env['SCU']:
	ConnectionSML = env.Library('ConnectionSML', 'ConnectionSML.cxx')
else:
	ConnectionSML = env.Library('ConnectionSML', Glob('src/*.cpp'))

env.Install('$PREFIX/lib', ConnectionSML)

