#import <XCTest/XCTest.h>

#include "TestHelpers.hpp"
#include "ChunkingTests.hpp"

#import "XCTestDefines.h"

TEST_SETUP(ChunkingTests)

XC_TEST(testAllTestTypes)
XC_TEST(testBlocksWorldHierarchical)
XC_TEST(testBUNCPS0)
XC_TEST(testBUNCPS1)
XC_TEST(testBUNCPS2)
XC_TEST(testBUNCPS3)
XC_TEST(testBUNCPS4)
XC_TEST(testBUNCPS5)
XC_TEST(testBUNCPS6FourLevel)
XC_TEST(testBUNCPS7withConstraints)
XC_TEST(testChunkRLProposal)
XC_TEST(testChunkedJustificationwithextras)
XC_TEST(testConflatedConstants)
XC_TEST(testConstraintPropfromBaseConds)
XC_TEST(testFauxOperator)
XC_TEST(testFauxSmemOperatorRHS)
XC_TEST(testJustificationRCnotUngroundedSTIs)
XC_TEST(testLiteralizationofNCandNCC)
XC_TEST(testLiteralizationwithBTConstraints)
XC_TEST(testLiteralizationwithBTConstraints2)
XC_TEST(testLiteralizationwithConstraints)
XC_TEST(testMaintainInstantiationSpecificIdentity)
XC_TEST(testNCDisjunction)
XC_TEST(testNCSimpleNoExist)
XC_TEST(testNCwithRCandLocalVariable)
XC_TEST(testNCwithRelationalConstraint)
XC_TEST(testNCC2CondsSimpleLiterals)
XC_TEST(testNCCComplex)
XC_TEST(testNCCfromBacktrace)
XC_TEST(testNCCSimpleLiterals)
XC_TEST(testNCCwithRelationalConstraint)
XC_TEST(testNoTopstateMatch)
XC_TEST(testOpaqueStateBarrier)
XC_TEST(testPromotedSTI)
XC_TEST(testReordererBadConjunction)
XC_TEST(testRepairNORTemporalConstraint)
XC_TEST(testResultOnOperator)
XC_TEST(testReteBugDeepvsDeep)
XC_TEST(testReteBugDeepvsTop)
XC_TEST(testRHSMathAbs)
XC_TEST(testRHSMathMixed)
XC_TEST(testRHSMath)
XC_TEST(testRHSUnboundMultivalue)
XC_TEST(testRLVariablization)
XC_TEST(testSimpleConstraintProp)
XC_TEST(testSimpleLiteralization)
XC_TEST(testSmemChunkDirect)
XC_TEST(testSMemChunkedQuery)
XC_TEST(testSTIVariablizationSameType)
XC_TEST(testSTIVariablization)
XC_TEST(testSTIwithreferents)
XC_TEST(testSuperstateIdentityOpaque)
XC_TEST(testLearn)
XC_TEST(testUngroundedinBTConstraint)
XC_TEST(testUngroundedLTI)
XC_TEST(testUngroundedMixed)
XC_TEST(testUngroundedRelationalConstraint)
XC_TEST(testUngroundedSTIPromotion)
XC_TEST(testUngroundedSTIs)
XC_TEST(testUnifyAmbiguousOutput)
XC_TEST(testUnifyChildrenResults)
XC_TEST(testUnifythroughTwoTracesFourDeep)
XC_TEST(testVrblzdConstraintonUngrounded)

@end
