#import <XCTest/XCTest.h>

#include "TestHelpers.hpp"
#include "TokenizerTest.hpp"

#import "XCTestDefines.h"

TEST_SETUP(TokenizerTest)

XC_TEST(testTokenizer01)
XC_TEST(testTokenizer02)
XC_TEST(testTokenizer03)
XC_TEST(testTokenizer04)
XC_TEST(testTokenizer05)
XC_TEST(testTokenizer06)
XC_TEST(testTokenizer07)
XC_TEST(testTokenizer08)
XC_TEST(testTokenizer09)
XC_TEST(testTokenizer10)
XC_TEST(testTokenizer11)
XC_TEST(testTokenizer12)
XC_TEST(testTokenizer13)
XC_TEST(testTokenizer14)
XC_TEST(testTokenizer15)
XC_TEST(testTokenizer16)
XC_TEST(testTokenizer17)
XC_TEST(testTokenizer18)
XC_TEST(testTokenizer19)
XC_TEST(testTokenizer20)
XC_TEST(testTokenizer21)
XC_TEST(testTokenizer22)
XC_TEST(testTokenizer23)
XC_TEST(testTokenizer24)
XC_TEST(testTokenizer25)
XC_TEST(testTokenizer26)
XC_TEST(testTokenizer27)
XC_TEST(testTokenizer28)
XC_TEST(testTokenizer29)
XC_TEST(testTokenizer30)
XC_TEST(testTokenizer31)
XC_TEST(testTokenizer32)
XC_TEST(testTokenizer33)
XC_TEST(testTokenizer34)
XC_TEST(testTokenizer35)
XC_TEST(testTokenizer36)
XC_TEST(testTokenizer37)
XC_TEST(testTokenizer38)
XC_TEST(testTokenizer39)
XC_TEST(testTokenizer40)
XC_TEST(testTokenizer41)
XC_TEST(testTokenizer42)
XC_TEST(testTokenizer43)
XC_TEST(testTokenizer44)
XC_TEST(testTokenizer45)
XC_TEST(testTokenizer46)
XC_TEST(testTokenizer47)
XC_TEST(testTokenizer48)

@end
