#!/usr/bin/python

import os
import sys

opts = Options()
opts.AddOptions(
	BoolOption( 'debug', 'Build with debugging symbols', 'yes' ),
)

# Create the environment using the options
env = Environment( options = opts, ENV = os.environ )
Help( opts.GenerateHelpText(env) )

#################
# Create configure context to configure the environment
conf = Configure( env )

# configure misc command line options
if conf.env['debug']:
	conf.env.Append(CPPFLAGS = ' -g3')
conf.env.Append(CPPFLAGS = ' -Wall')
conf.env.Append(CPPFLAGS = ' -Werror')

env = conf.Finish()

#################
# Build

import glob

prefix = '/usr/local'
soar_home = '~/soar/SoarSuite'

env.Prepend(CPPPATH = [	
	prefix + '/include/player-2.1',
	soar_home + '/Core/ClientSML/include',
	soar_home + '/Core/ElementXML/include',
	soar_home + '/Core/ConnectionSML/include',
])

libpath = [ 
	prefix + '/lib',
]

libadd = [ 
	'playerc++', 
	'playerc',
	'm', 
	'playerxdr', 
	'playererror', 
	'ClientSML', 
	'ConnectionSML', 
	'ElementXML', 
]

env.Append(LIBS = libadd, LIBPATH = libpath)
soarplayer = env.Program('soarplayer', glob.glob('*.cpp'))

