#!/usr/bin/python
import glob

Import('env')
env = env.Copy()
env.Prepend(CPPPATH = [	'../../Core/ClientSML/include',
			'../../Core/ElementXML/include',
			'../../Core/ConnectionSML/include'])

libadd = [ 'ClientSML', 
	   'ConnectionSML',
	   'ElementXML', 
	   ]

libpath = [ '../../Core/ClientSML',
	    '../../Core/ConnectionSML',
	    '../../Core/ElementXML', 
	    ]

env.Append(LIBS = libadd, LIBPATH = libpath)
FilterC = env.Program('FilterC', glob.glob('*.cpp'))
env.Install('#SoarLibrary/bin', FilterC)
