#!/usr/bin/python
import sys

Import('env')
env = env.Clone()

env.Prepend(CPPPATH = [	'#ClientSML/src',
			'#ElementXML/src',
			'#ConnectionSML/src'])

libadd = [ 'ClientSML', 
	   'ConnectionSML',
	   'ElementXML', 
	   ]

libpath = [ '$PREFIX/lib' ]

env.Append(LIBS = libadd, LIBPATH = libpath)
SoarTextIO = env.Program('SoarTextIO', Glob('src/*.cpp'))
env.Install('$PREFIX/bin', SoarTextIO)

