#!/usr/bin/python
import glob
import sys

Import('env')
env = env.Clone()
env.Prepend(CPPPATH = [	'../../Core/ClientSML/include',
			'../../Core/ElementXML/include',
			'../../Core/ConnectionSML/include'])

libadd = [ 'ClientSML', 
	   'ConnectionSML',
	   'ElementXML', 
	   ]

libpath = [ '../../Core/ClientSML',
	    '../../Core/ConnectionSML',
	    '../../Core/ElementXML', 
	    ]

if env['static']:
	libadd.extend(['SoarKernelSML','CommandLineInterface', 'gSKI', 'SoarKernel'])
	libpath.extend(['../../Core/KernelSML','../../Core/CLI','../../Core/gSKI','../../Core/SoarKernel',])
	   

env.Append(LIBS = libadd, LIBPATH = libpath)
TestMultiAgent = env.Program('TestMultiAgent', glob.glob('*.cpp'))
env.Install('#SoarLibrary/bin', TestMultiAgent)
