//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Dss.Core.Attributes;
using System;
using System.Collections.Generic;
using interopservices = System.Runtime.InteropServices;
using System.Reflection;

[assembly: ServiceDeclaration(DssServiceDeclaration.ServiceBehavior)]
[assembly: interopservices.ComVisible(false)]
[assembly: AssemblyTitle("Soar MSR Service")]
[assembly: AssemblyProduct("Soar MSR Service")]
[assembly: AssemblyVersion("1.0")]
[assembly: AssemblyCopyright("Written by Jonathan Voigt, March 2008")]
[assembly: AssemblyDescription("Control robots in MSRS using Soar. Built for MSRS V1.5. This version is freely available.")]
[assembly: AssemblyCompany("University of Michigan")]

