#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
Import('env')
clone = env.Clone()

clone.Prepend(CPPPATH = ['src'])

if env['SCU']:
	if env['STATIC_LINKED']:
		ElementXML = clone.Library('ElementXML', 'ElementXML.cxx')
	else:
		ElementXML = clone.SharedLibrary('ElementXML', 'ElementXML.cxx')
else:
	if env['STATIC_LINKED']:
		ElementXML = clone.Library('ElementXML', Glob('src/*.cpp'))
	else:
		ElementXML = clone.SharedLibrary('ElementXML', Glob('src/*.cpp'))

env.Install('$PREFIX/lib', ElementXML)
