#!/usr/bin/perl

$appendix = "_PII";
@versions = ("HEAVY", "STD", "V2", "LITE", "LITE_2", "LITE_3", "V3", "V3_3");
#@versions = ("HEAVY", "STD");


foreach $v (@versions)  {
    open( OPT, ">tempOptions" ) or die "Can't open options file\n";
    print OPT "$v\n";
    close( OPT );

    print "*************************************************************\n";
    print "                Making Version: $v \n";
    print "*************************************************************\n";
    print "Making Kernel...\n";
    `make clean`;
    `make version`;
    
    die "No soar lib!\n" unless ( -e "libsoarkernel.a" );
    
    print "Making tcl-Interface...\n";
    chdir("../tcl-interface" );
    `make clean`;
    `make soartk`;
    `mv -f soartk8.2 soartk8.2_$v$appendix`;

    print "Making shell interface...\n";
    chdir("../new-unix-interface" );
    `make clean`;
    `make`;
    `mv -f soar_app soar_$v$appendix`;
    chdir("../kernel" );
}
    
    
