#!/usr/bin/python

Import('compEnv')
env = compEnv.Clone()

if env['STATIC_LINKED']:
	print "Skipping TestExternalLibrary due to static linkage"
else:
	TestExternalLibrary = env.Program('TestExternalLibrary', Glob('*.cpp'))
	env.Install('$PREFIX/bin', TestExternalLibrary)

