#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#

Import('compEnv')
env = compEnv.Clone()

if env['STATIC_LINKED']:
	print "Skipping TestExternalLibrary due to static linkage"
else:
	TestExternalLibrary = env.Program('TestExternalLibrary', Glob('*.cpp'))
	Install('$PREFIX/bin', TestExternalLibrary)

