#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
Import('env')

TestExternalLibraryLib = env.SharedLibrary('TestExternalLibraryLib', 'lib.cpp')
TestExternalLibrary = env.Program('TestExternalLibrary', 'TestExternalLibrary.cpp')
env.Alias('TestExternalLibrary', env.Install('$OUT_DIR', [TestExternalLibrary, TestExternalLibraryLib]))
