#!/bin/sh 

if test -n "$2"; then
  files="$2"
else
  files=`(cd man;ls | grep .n | sed s/\\\.n//g)`
fi

echo Updating $files

if [ "$1" = "-cat" ]; then
  for f in $files
  do
    echo Updating cat form of $f
    rm -f cat/$f.n
  
    cd man

    nroff -man $f.n > ../cat/$f.n
    cd ..
  done
fi

if [ "$1" = "-html" ]; then
  for f in $files
  do
    echo Updating html form of $f
    rm -f html/$f.html

    man2html man/$f.n > html/$f.html
  done
fi



