#!/usr/bin/python
import sys

Import('env')
env = env.Clone()
env.Prepend(CPPPATH = ['$PREFIX/include'])

libadd = [ 'ClientSML', 'ConnectionSML', 'ElementXML', ]
if env['STATIC_LINKED']:
        libadd = [ 'ClientSML', 'ConnectionSML', 'ElementXML', 'SoarKernelSML', 'SoarKernel', 'CommandLineInterface', 'sqlite3' ]

libpath = [ '$PREFIX/lib' ]

env.Append(LIBS = libadd, LIBPATH = libpath)
soar2soar = env.Program('soar2soar', Glob('*.cpp'))
env.Install('$PREFIX/bin', soar2soar)

# Resources
env.Install('$PREFIX/share/soar/Demos/soar2soar', ['#../Soar2Soar/agents', '#../Soar2Soar/environments'])
env.Clean(soar2soar, env.FindInstalledFiles())

