#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
Import('compEnv')

soar2soar = compEnv.Program('soar2soar', Glob('*.cpp'))
compEnv.Install('$PREFIX/bin', soar2soar)

# Resources
Import('InstallDir')
InstallDir(soar2soar, '$PREFIX/share/soar/Soar2Soar/agents', '#../Soar2Soar/agents')
InstallDir(soar2soar, '$PREFIX/share/soar/Soar2Soar/environments', '#../Soar2Soar/environments')
compEnv.Clean(soar2soar, '$PREFIX/share/soar/Soar2Soar')

