#!/usr/bin/python
import sys

Import('compEnv')
env = compEnv.Clone()

soar2soar = env.Program('soar2soar', Glob('*.cpp'))
env.Install('$PREFIX/bin', soar2soar)

# Resources
env.Install('$PREFIX/share/soar/Demos/soar2soar', ['#../Soar2Soar/agents', '#../Soar2Soar/environments'])
env.Clean(soar2soar, env.FindInstalledFiles())

