#!/usr/bin/python
import os
import SoarSCons

Import('env')
env = env.Clone()

theJar = '#Tools/VisualSoar/VisualSoar.jar';
sources = SoarSCons.JavaSources('src')

Depends(theJar, 'build.xml')

env.Command(theJar, sources, 'ant -q', chdir=1)

