#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
Import('env')
Import('javaRunAnt')
Soar2D = javaRunAnt('Soar2D', 'soar-soar2d', 'src')
smljar = "$PREFIX/share/java/soar-smljava-" + env['SOAR_VERSION'] + ".jar"
env.Depends(Soar2D, smljar)
debuggerjar = "$PREFIX/share/java/soar-debugger-" + env['SOAR_VERSION'] + ".jar"
env.Depends(Soar2D, debuggerjar)

