#!/bin/sh
# Create random training and test sets using divide.py and run each learner on them

if [ "$#" != 4 ]
then
	echo 'usage: cmplearn <num train> <num test> <num neighbors> <data>'
	exit 1
fi

python divide.py $1 $2 "$4" > temp

echo 'python ref:'
python lwrtest.py $3 temp

echo 'C++ LSQR:'
lwrtest l $3 temp

echo 'C++ Ridge:'
lwrtest r $3 temp

rm temp
