#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
import os
Import('env', 'InstallDir')

subdirs = ['TestExternalLibrary']

if (os.sys.platform == 'win32' and env["MSVC_VERSION"] == "14.0") or (os.sys.platform != 'win32'):
	subdirs.append('Prototype-UnitTesting')

tests = []
for d in subdirs:
	script = os.path.join(d, 'SConscript')
	tests.extend(SConscript(script))

prototype_unittesting_tests = InstallDir(env, '$OUT_DIR/Tests/', 'Prototype-UnitTesting/Tests')

env.Alias('tests', tests + prototype_unittesting_tests)
