#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
import sys

Import('env', 'InstallDir')
clone = env.Clone()

libadd = ['Soar']

if sys.platform == "darwin":
	if GetOption('platform') == '64':
		libadd.append('cppunit-osx-64')
	else:
		libadd.append('cppunit-osx')
else:
	if GetOption('platform') == '64':
		libadd.append('cppunit-linux-64')
	else:
		libadd.append('cppunit-linux')

clone.Prepend(LIBS = libadd, LIBPATH = ['lib'], CPPPATH = env.Dir('src').srcnode())
Tests = clone.Program('Tests', Glob('src/*.cpp'))
env.Alias('Tests', [env.Install('$OUT_DIR', Tests)] + InstallDir(env, '$OUT_DIR/test_agents', 'Agents'))
