import os

def srcp(p):
	return '../src/' + p

def srca(p):
	return '../src/algorithms/' + p

env = Environment(
	CPPPATH = os.environ.get('CPATH','').split(':') + [srcp('.'), srca('.'), '../eigen' ],
	#CPPFLAGS = ['-O3', '-Wno-enum-compare'],
	CPPFLAGS = ['-g', '-Wno-enum-compare'],
	LINKFLAGS = ['-g'],
	LIBPATH = os.environ.get('LD_LIBRARY_PATH', '').split(':'),
	LIBS = [ 'rt', 'ode', 'opencv_core', 'opencv_ml' ],
)

srcs = [
	srcp('common.cpp'),
	srcp('mat.cpp'),
	srcp('relation.cpp'),
	srcp('serialize.cpp'),
	srcp('timer.cpp'),
	srcp('scene_sig.cpp'),
	srcp('collision.cpp'),
	srcp('sgnode.cpp'),
	srca('foil.cpp'),
	srca('linear.cpp'),
	srca('lda.cpp'),
]

run_lda_src = [
	srcp('common.cpp'),
	srcp('mat.cpp'),
	srca('lda.cpp'),
	'run_lda.cpp',
]

test_foil_src = [
	srcp('common.cpp'),
	srcp('relation.cpp'),
	srca('foil.cpp'),
	'test_foil.cpp'
]

test_intervalset_src = [
	srcp('common.cpp'),
	srcp('relation.cpp'),
	'test_intervalset.cpp'
]

test_csp_src = [
	srcp('common.cpp'),
	srcp('relation.cpp'),
	srca('foil.cpp'),
	'test_csp.cpp'
]

#env.Program('test_svs2', srcs + ['test_svs2.cpp'])
env.Program('run_lda', run_lda_src)
env.Program('test_foil', test_foil_src)
env.Program('test_intervalset', test_intervalset_src)
env.Program('test_csp', test_csp_src)
