#!/bin/sh
# filter to convert Tk and Tcl man pages to html equivalents
# does not do any linking !!!!
#
# This code taken from Mike Hopkirk's (hops@x.co.uk) w3get package,
# -- the file tk2html.

TOP=.
AWK=/bin/nawk

cat  $1 | 
    sed  -e 's/\\-/-/g' \
         -e 's/\\[0&]/  /g' \
         -e 's/&/\&amp;/g' \
         -e 's/</\&lt;/g' \
         -e 's/>/\&gt;/g' \
         -e 's/\\|//g' \
         -e 's/\\e/\\/g'     |
    ${AWK} -f ${TOP}/man2html.awk | 
     sed -e 's^\\fB\([^\\]*\)\\fR^<B>\1</B></I>^g' \
        -e 's^\\fI\(.[^\\]*\)\\fR^<I>\1</I></B>^g' \
        -e 's^\\fB^<B>^g' \
        -e 's^\\fI^<I>^g' \
        -e 's^\\f[RP]^</B></I>^g' \
        -e 's/^.[LP]P/<P>/' \
        -e 's/^.br/<BR>/' \
        -e 's/^\.DS.*/<pre>/' \
        -e 's$^\.DE.*$</pre>$' \
        -e 's/^\.nf */<pre>/' \
        -e 's$^\.fi *$</pre>$' \
        -e 's$^\.BE *$</pre><HR>$' \
        -e 's/^\.RS.*/<UL>/' \
        -e 's$^\.RE.*$</UL>$' \
        -e 's^\.SH *"*\([^"]*\)"*^</pre><H2>\1</H2>^' \
        -e 's/^\.[a-zA-Z]*.*//'

# The above handling for font mapping to html works correctly in about 95% of 
# the cases, the others turn out stacking the font setting so you get the 
# font bleeding since it isn't being turned off in the correct places. 
# To correct we would have to record the current ( non-default) font and 
# explicitly turn it off when another font change is detected.
# Which would make multiple styles impossible concurrently which seems to
# be the case anyway....

