env = Environment(
	CPPPATH = ['/usr/local/include'],
	LIBPATH = ['/usr/local/lib'],
	LIBS = 'pthread glut osg osgViewer osgDB osgUtil osgGA osgText OpenThreads osgFX'.split(),
	CPPFLAGS = ['-O3'],
)

env.Program('viewer', ['viewer.cpp', 'scene.cpp'])
