//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using Microsoft.Dss.Core.Attributes;
using System.Xml.Serialization;
using W3C.Soap;
using compression = System.IO.Compression;
using contractmodel = Microsoft.Dss.Services.ContractModel;
using io = System.IO;
using pxintro = Robotics.Intro.Proxy;
using reflection = System.Reflection;

[assembly: ContractNamespace(pxintro.Contract.Identifier, ClrNamespace="Robotics.Intro.Proxy")]


namespace Robotics.Intro.Proxy
{
    
    /// <summary>
    /// Contract
    /// </summary>
    [XmlTypeAttribute(IncludeInSchema=false)]
    public sealed class Contract
    {
        /// <summary>
        /// Namespace
        /// </summary>
        public const string Identifier = "http://schemas.tempuri.org/2006/08/intro.html";
        /// The Dss Service dssModel Contract(s)
        public static List<contractmodel.ServiceSummary> ServiceModel()
        {
            List<contractmodel.ServiceSummary> services = null;
            io.Stream stream = null;
            try
            {
                string Resource = @"Robotics.Intro.Resources.DssModel.dss";
                stream = reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream(Resource);
                compression.GZipStream compressionStream = new compression.GZipStream(stream, compression.CompressionMode.Decompress, true);
                XmlSerializer serializer = new XmlSerializer(typeof(List<contractmodel.ServiceSummary>));
                services = (List<contractmodel.ServiceSummary>)serializer.Deserialize(compressionStream);
                compressionStream.Close();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error retrieving Dss Service Model: ", ex.Message);
            }
            finally
            {
                if (stream != null)
                {
                    stream.Close();
                    stream = null;
                }
            }
            return services;

        }
    }
    /// <summary>
    /// Intro State
    /// </summary>
    [DataContract()]
    [XmlRootAttribute("IntroState", Namespace="http://schemas.tempuri.org/2006/08/intro.html")]
    public class IntroState : System.ICloneable
    {
        private bool _motorOn;
        /// <summary>
        /// Motor On
        /// </summary>
        [DataMember()]
        public bool MotorOn
        {
            get
            {
                return this._motorOn;
            }
            set
            {
                this._motorOn = value;
            }
        }
        public void CopyTo(IntroState target)
        {
            target.MotorOn = this.MotorOn;
        }
        public virtual object Clone()
        {
            IntroState newobj = new IntroState();
            CopyTo(newobj);
            return newobj;

        }
    }
    /// <summary>
    /// Intro Operations
    /// </summary>
    [XmlTypeAttribute(IncludeInSchema=false)]
    public class IntroOperations : PortSet<DsspDefaultLookup, DsspDefaultDrop, Get, Replace>
    {
        // Post DsspDefaultLookup and return the response port.
        public virtual PortSet<LookupResponse,Fault> DsspDefaultLookup(LookupRequestType body)
        {
            DsspDefaultLookup op = new DsspDefaultLookup();
            op.Body = body ?? new LookupRequestType();
            this.Post(op);
            return op.ResponsePort;

        }
        // Post DsspDefaultLookup and return the response port.
        public virtual PortSet<LookupResponse,Fault> DsspDefaultLookup()
        {
            DsspDefaultLookup op = new DsspDefaultLookup();
            op.Body = new LookupRequestType();
            this.Post(op);
            return op.ResponsePort;

        }
        // Post DsspDefaultDrop and return the response port.
        public virtual PortSet<DefaultDropResponseType,Fault> DsspDefaultDrop(DropRequestType body)
        {
            DsspDefaultDrop op = new DsspDefaultDrop();
            op.Body = body ?? new DropRequestType();
            this.Post(op);
            return op.ResponsePort;

        }
        // Post DsspDefaultDrop and return the response port.
        public virtual PortSet<DefaultDropResponseType,Fault> DsspDefaultDrop()
        {
            DsspDefaultDrop op = new DsspDefaultDrop();
            op.Body = new DropRequestType();
            this.Post(op);
            return op.ResponsePort;

        }
        // Post Get and return the response port.
        public virtual PortSet<IntroState,Fault> Get(GetRequestType body)
        {
            Get op = new Get();
            op.Body = body ?? new GetRequestType();
            this.Post(op);
            return op.ResponsePort;

        }
        // Post Replace and return the response port.
        public virtual PortSet<DefaultReplaceResponseType,Fault> Replace(IntroState body)
        {
            Replace op = new Replace();
            op.Body = body ?? new IntroState();
            this.Post(op);
            return op.ResponsePort;

        }
    }
    /// <summary>
    /// Get
    /// </summary>
    [XmlTypeAttribute(IncludeInSchema=false)]
    public class Get : Get<GetRequestType, PortSet<IntroState, Fault>>
    {
        public Get()
        {
        }
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body)
        {
        }
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, Microsoft.Ccr.Core.PortSet<IntroState,W3C.Soap.Fault> responsePort) : 
                base(body, responsePort)
        {
        }
    }
    /// <summary>
    /// Replace
    /// </summary>
    [XmlTypeAttribute(IncludeInSchema=false)]
    public class Replace : Replace<IntroState, PortSet<DefaultReplaceResponseType, Fault>>
    {
        public Replace()
        {
        }
        public Replace(IntroState body) : 
                base(body)
        {
        }
        public Replace(IntroState body, Microsoft.Ccr.Core.PortSet<Microsoft.Dss.ServiceModel.Dssp.DefaultReplaceResponseType,W3C.Soap.Fault> responsePort) : 
                base(body, responsePort)
        {
        }
    }
}
