#!/usr/bin/python
import glob

Import('env')
env = env.Copy()
env.Prepend(CPPPATH = ['src', 'include',])

ElementXML = env.SharedLibrary('ElementXML', glob.glob('src/*.cpp'))
env.Install('#SoarLibrary/lib', ElementXML)

#perhaps this is required for linking on osx?
ElementXMLStatic = env.StaticLibrary('ElementXML', glob.glob('src/*.cpp'))
env.Install('#SoarLibrary/lib', ElementXMLStatic)
