#!/usr/bin/python
import glob
import shutil

Import('env')
env = env.Copy()

#FIXME:
# THIS FILE IS A COMPLETE HACK.

# $JAVAC $JAVACFLAGS -d ${TARGET.attributes.java_classdir} -sourcepath ${SOURCE.dir.rdir()} $SOURCES
#env.Replace(JAVACCOM = '$JAVAC $JAVACFLAGS -d ${TARGET.attributes.java_classdir} -classpath Core/ClientSMLSWIG/Java/sml.jar:. -sourcepath Tools/VisualSoar/Source Tools/VisualSoar/Source/edu/umich/visualsoar/VisualSoar.java')
env.Replace(JAVACCOM = '$JAVAC $JAVACFLAGS -d ${TARGET.attributes.java_classdir} -classpath Core/ClientSMLSWIG/Java/sml.jar:. -sourcepath Tools/VisualSoar/Source $SOURCES')

javacStep = env.Java(target = 'classes', source = 'Source')

# The usual jar command does not work. It only finds and jars class files and we need a bunch of other junk.
# If you list files specifically, it includes a full path with them.

# it might work in the case of VisualSoar but we'll stick to the old format in case it changes.
#copySources = [
#	       glob.glob('src/mac/*'),
#	      ]

#def copyFiles(target, source, env):
#	prefix = 'Tools/VisualSoar/'
#
#	for file in glob.glob(prefix + 'src/mac/*'):
#		shutil.copyfile(file, file.replace('/src/','/classes/'))
	
#copyStep = env.Command('classes/mac/boat.gif', copySources, copyFiles)
env['JAVACFLAGS'] = ' -source 1.4 '
jarStep = env.Command('#Tools/VisualSoar/VisualSoar.jar', 'classes', 'jar cfm Tools/VisualSoar/VisualSoar.jar Tools/VisualSoar/Source/META-INF/MANIFEST.MF -C Tools/VisualSoar/classes .')

#env.Depends(jarStep, copyStep)
#env.Depends(copyStep, javacStep)
env.Depends(jarStep, javacStep)

env.Install('#SoarLibrary/bin', '#Tools/VisualSoar/VisualSoar.jar')

env.Clean('classes', 'classes')
