#!/bin/sh

root=../../../../out
export LD_LIBRARY_PATH=$root/lib:$HOME/local/lib:$LD_LIBRARY_PATH
soar=$root/bin/s

while test -n "$1"
do
	case "$1" in
	-g)
		debug=1
		;;
	-j)
		java=1
		;;
	esac
	shift
done

if test "$java" == "1"
then
	socat system:"java RobotClient" unix-connect:env,retry=100 &
else
	#python splintersim.py &
	#envid=$!
	#socat system:./splintersim unix-connect:env,retry=100 &
	#splintersim3 | python splintersim3_disp.py &
	splintersim3 >/dev/null &
	envid=`ps | awk '$4 ~ "splintersim3" {print $1}'`
fi

if test "$debug" == "1"
then
	gdb --args $soar agent/robot.soar
else
	$soar agent/robot.soar
fi

if test "$java" == "1"
then
	pids=`ps x | awk '/RobotClient/ { print $1 }'`
	if test -n "$pids"
	then
		kill $pids
	fi
else
	kill $envid
fi
