#!/usr/bin/python
import glob
import sys

Import('env')
env = env.Clone()
env.Prepend(CPPPATH = [	
			'include',
			'src',
			'../Core/ClientSML/include',
			'../Core/KernelSML/include',
			'../Core/CommandLineInterface/include',
			'../Core/SoarKernel/include',
			'../Core/ElementXML/include',
			'../Core/ConnectionSML/include'])

if sys.platform == "darwin":
	if env[ 'processor' ] != 'powerpc':
		libadd = [ 'ClientSML', 
			   'ConnectionSML',
			   'ElementXML', 
			   'cppunit-osx',
			   ]
	else:
		libadd = [ 'ClientSML', 
			   'ConnectionSML',
			   'ElementXML', 
			   'cppunit-osxppc',
			   ]
else:
	libadd = [ 'ClientSML', 
		   'ConnectionSML',
		   'ElementXML', 
		   'cppunit-linux',
		   ]

if sys.platform == 'cygwin':
	libadd.extend(['ws2_32',])

libpath = [ '../Core/ClientSML',
	    '../Core/ConnectionSML',
	    '../Core/ElementXML', 
	    '.',
	    ]

env.Append(LIBS = libadd, LIBPATH = libpath)
Tests = env.Program('Tests', glob.glob('src/*.cpp'))
env.Install('#SoarLibrary/bin', Tests)
