#!/bin/sh

export LD_LIBRARY_PATH=../../../../out/lib:$HOME/local/lib
soar=../../../../out/bin/s

#socat unix-connect:env,retry=10 system:'python cursor.py' &

if [ "$1" == "-g" ]
then
	gdb --args $soar cursor.soar
else
	$soar cursor.soar
fi

