#!/usr/bin/python
import glob
import sys

Import('env')
env = env.Clone()
env.Prepend(CPPPATH = [	
			'include',
			'src',
			'../../Core/ClientSML/include',
			'../../Core/ElementXML/include',
			'../../Core/ConnectionSML/include'])

libadd = [ 'ClientSML', 
	   'ConnectionSML',
	   'ElementXML', 
	   ]

libpath = [ '../../Core/ClientSML',
	    '../../Core/ConnectionSML',
	    '../../Core/ElementXML', 
	    ]

env.Append(LIBS = libadd, LIBPATH = libpath)

if env['scu']:
	QuickLink = env.Program('QuickLink', 'QuickLink.cxx')
else:
	QuickLink = env.Program('QuickLink', glob.glob('src/*.cpp'))
env.Install('#SoarLibrary/bin', QuickLink)
