#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
import os
Import('env')

tests = ['TestSMLEvents', 'TestSMLPerformance', 'TestSoarPerformance', 'TestExternalLibrary', 'UnitTests']

for d in tests:
	script = os.path.join(d, 'SConscript')
	SConscript(script)

env.Alias('Tests', tests)
