#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
import os
Import('env')

subdirs = ['TestSMLEvents', 'TestSMLPerformance', 'TestSoarPerformance', 'TestExternalLibraryLib', 'TestExternalLibrary']

for d in subdirs:
	script = '../CoreTests/%s/SConscript' % d
	print "Processing", script + "..."
	SConscript(script, variant_dir=os.path.join(env['BUILD_DIR'], d), dupicate=0)

