#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#

Import('compEnv')
env = compEnv.Clone()

SoarScratchPad = env.Program('soarscratchpad', Glob('*.cpp'))
env.Install('$PREFIX/bin', SoarScratchPad)

