#ifndef ILINK_ABSTRACTION_SPEC_MODULE
#define ILINK_ABSTRACTION_SPEC_MODULE



class InputLinkSpec
{
private:
	enum parseStage {
		READING_CONTROL_STRUCTURE,
		READING_IDENTIFIER,
		READING_ATTRIBUTE,
		READING_VALUE_TYPE,
		READING_START_VALUE,
		READING_UPDATE,
		READING_CREATE_ON,
		READING_DELETE_ON,
		READING_COMPLETED,
	};
public:


};


#endif ILINK_ABSTRACTION_SPEC_MODULE
