#!/usr/bin/python
import sys

Import('compEnv')
env = compEnv.Clone()

TOHSML = env.Program('TOHSML', Glob('*.cpp'))
env.Install('$PREFIX/bin', TOHSML)

# Install resources
env.Install('$PREFIX/share/soar/Demos', 'towers-of-hanoi-SML.soar')
env.Clean(TOHSML, env.FindInstalledFiles())

