#!/usr/bin/python
import sys

Import('env')
env = env.Clone()

env.Prepend(CPPPATH = [	'#ClientSML/src', '#ElementXML/src', '#ConnectionSML/src'])

libadd = [ 'ClientSML', 'ConnectionSML', 'ElementXML', ]
if env['STATIC_LINKED']:
        libadd = [ 'ClientSML', 'ConnectionSML', 'ElementXML', 'SoarKernelSML', 'SoarKernel', 'CommandLineInterface', 'sqlite3' ]

libpath = [ '$PREFIX/lib' ]

env.Append(LIBS = libadd, LIBPATH = libpath)
TOHSML = env.Program('TOHSML', Glob('*.cpp'))
env.Install('$PREFIX/bin', TOHSML)
env.Install('$PREFIX/share/soar/Demos', 'towers-of-hanoi-SML.soar')

