#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
import os

Import('compEnv')

TOHSML = compEnv.Program('TOHSML', Glob('*.cpp'))
compEnv.Install('$PREFIX/bin', TOHSML)

# Install resources
compEnv.Install('$PREFIX/share/soar/Demos', 'towers-of-hanoi-SML.soar')
compEnv.Clean(TOHSML, os.path.join('$PREFIX/share/soar/Demos', 'towers-of-hanoi-SML.soar'))

