#!/usr/bin/python
import glob

Import('env')
env = env.Clone()
env.Append(CPPFLAGS = ' -fno-strict-aliasing')
env.Prepend(CPPPATH = [ 'src', 
			'include', 
			'../ElementXML/include'])

SQLite = env.SharedObject('sqlite3.os', 'sqlite/sqlite3.c')

if env['scu']:
	SoarKernel = env.StaticLibrary('SoarKernel', 'SoarKernel.cxx')
else:
	SoarKernel = env.StaticLibrary('SoarKernel', glob.glob('src/*.cpp'))
env.Install('#SoarLibrary/lib', SoarKernel)
