#!/usr/bin/python

import os

Import('env')
env = env.Clone()

env.Append(CPPFLAGS = ' -fno-strict-aliasing')
env.Prepend(CPPPATH = ['src', '#ElementXML/src'])

sql_env = env.Clone()
sql_env.Append(CPPFLAGS = ' -w')
SQLite = sql_env.StaticLibrary('sqlite3', 'sqlite/sqlite3.c')

if env['SCU']:
	SoarKernel = env.StaticLibrary('SoarKernel', 'SoarKernel.cxx')
else:
	SoarKernel = env.StaticLibrary('SoarKernel', Glob('src/*.cpp'))

env.Install('$PREFIX/lib', SoarKernel)
env.Install('$PREFIX/lib', SQLite)

# Install resources
# Gotta install these all specifically because of the way the SCons works.
# Doing the following doesn't work once include exists already:
# includeTargetDir = '$PREFIX/include'
# env.InstallAs(target = includeTargetDir, source = '#shared')

# find shared -type d | grep -v ".svn"

sharedIncludes = env.Glob('#shared/*.h')
sharedIncludes.append(env.Glob('#shared/*.hpp'))
env.Install('$PREFIX/include', sharedIncludes)

# Broken, not easy to fix. Installs .svn folders.
sharedIncludeSubfolders = ['#shared/stlsoft', '#shared/winstl', '#shared/msvc', '#shared/unixstl', ]
env.Install('$PREFIX/include', sharedIncludeSubfolders)

env.Clean(SoarKernel, env.FindInstalledFiles())

