#!/usr/bin/python

Import('env')
env = env.Clone()

env.Prepend(CPPPATH = ['src', 
		       'include', 
		       '#SoarKernel/include', 
		       '#ElementXML/include', 
		       '#ConnectionSML/include', 
		       '#KernelSML/include', ])

if env['SCU']:
	CommandLineInterface = env.Library('CommandLineInterface', 'CommandLineInterface.cxx')
else:
	CommandLineInterface = env.Library('CommandLineInterface', Glob('src/*.cpp'))

env.Install('$PREFIX/lib', CommandLineInterface)

