#!/bin/sh

agent=agent/planner.soar 

ntargets=$1
shift
seeds="$*"

for c1x in e w; do
	for c1y in n s; do
		for t1x in e w; do
			for t1y in n s; do
				env_args="-h 2 $s $ntargets $c1x $c1y $t1x $t1y"
				echo "./run -s $agent -e '$env_args' run"
			done
		done
	done
done

for direction in "1 0" "-1 0" "0 1" "0 -1"
do
	for s in $seeds
	do
	
	done
done
