#!/bin/sh

agent=agent/learner.soar 

ncubes=$1
ntargets=$2
nsteps=$3
shift; shift; shift
seeds="$*"

for touching in `seq $((ncubes-1))`
do
	for side in l r t b
	do
		for direction in "1 0" "-1 0" "0 1" "0 -1"
		do
			for s in $seeds
			do
				env_args="-h 1 $s $ncubes $ntargets $touching $side"
				remote_args="fixed $nsteps $s $direction"
			
				echo "./run -s $agent -r '$remote_args' -e '$env_args' 'run $((nsteps+2))'"
			done
		done
	done
done

for direction in "1 0" "-1 0" "0 1" "0 -1"
do
	for s in $seeds
	do
		env_args="-h 1 $s $ncubes $ntargets"
		remote_args="fixed $nsteps $s $direction"
	
		echo "./run -s $agent -r '$remote_args' -e '$env_args' 'run $((nsteps+2))'"
	done
done
