#!/bin/sh

NTRAIN=50
NTEST=10
TRAIN_CHUNK=10

WD="data/lc-`date +"%d:%H:%M:%S"`"
mkdir $WD

TRAIN_SCEN="$WD/train_scen"
TEST_SCEN="$WD/test_scen"
RESULTS="$WD/results"

./gen_scenarios 3 10 1 2 3 | head -n $NTRAIN >$TRAIN_SCEN
./gen_scenarios 3 2 2 | head -n $NTEST >$TEST_SCEN

rm -f models/*

train_block=0

while [ "$((train_block * TRAIN_CHUNK + 1< NTRAIN))" -eq 1 ]
do
	blockdir="$WD/block$train_block"
	mkdir $blockdir
	
	train_start=$((train_block * TRAIN_CHUNK + 1))
	train_stop=$((train_start + TRAIN_CHUNK - 1))
	echo "training on scenarios $train_start - $train_stop"
	
	sed -n -e "${train_start},${train_stop}p" $TRAIN_SCEN > train_batch
	./run_scenarios train train_batch || exit 1
	
	rm -f predictions/*
	./run_scenarios test $TEST_SCEN || exit 1
	
	means=''
	names=''
	# aggregate statistics
	for f in predictions/*
	do
		n=`basename $f`
		n=${n%.*}
		m=`awk '{print $NF}' $f | tb mean`
		names="$names $n"
		means="$means $m"
		echo $n $m
	done
	if [ ! -f "$RESULTS" ]
	then
		echo "$names" > "$RESULTS"
	fi
	echo "$means" >> "$RESULTS"
	
	cp -r predictions $blockdir
	cp -r models $blockdir
	cp -r trees $blockdir
	
	train_block=$((train_block+1))
done | tee $WD/log

