#!/bin/bash

NTRAIN=100
NTEST=50
TRAIN_CHUNK=20
TRAIN_SEEDS="1 2 3 4 5 6 7 8 9 10"
TEST_SEEDS="101 102 103 104 105 106 107 108 109 110"

WD="data/$1/lc-`date +"%d:%H:%M:%S"`"
mkdir -p $WD

TRAIN_SCEN="$WD/train_scen"
TEST_SCEN="$WD/test_scen"
RESULTS="$WD/results"

# deterministic shuffle
dshuf() {
	shuf --random-source=<(awk -v s=${1:-1} 'BEGIN { srand(s); while (1) { print rand() } }')
}

./gen_scenarios1 2 1 10 $TRAIN_SEEDS | dshuf 1 | head -n $NTRAIN >$TRAIN_SCEN
./gen_scenarios1 2 1 1 $TEST_SEEDS | dshuf 2 | head -n $NTEST >$TEST_SCEN

NTRAIN=`wc -l<"$TRAIN_SCEN"`
NTEST=`wc -l<"$TEST_SCEN"`

rm -f models/*

train_block=0

while true
do
	train_start=$((train_block * TRAIN_CHUNK + 1))
	if [ $train_start -gt $NTRAIN ]
	then
		break
	fi

	train_stop=$(((train_block + 1) * TRAIN_CHUNK))
	if [ $train_stop -gt $NTRAIN ]
	then
		train_stop=$NTRAIN
	fi
	
	echo "training on scenarios $train_start - $train_stop"

	rm -f trees/*

	blockdir="$WD/block$train_block"
	mkdir $blockdir
	sed -n -e "${train_start},${train_stop}p" $TRAIN_SCEN > train_batch
	./run_scenarios train train_batch || exit 1
	cp /tmp/atom_names $WD
	cp -r models $blockdir
	cp -r trees $blockdir
	
	rm -f predictions/*
	./run_scenarios test $TEST_SCEN || exit 1
	
	means=''
	names=''
	# aggregate statistics
	for f in predictions/*.{em,lwr}
	do
		if [ ! -f "$f" ]
		then
			continue
		fi
		n=`basename $f`
		n=${n%.*}
		m=`awk '{print $NF}' $f | grep -v nan | tb mean`
		names="$names $n"
		means="$means $m"
		echo $n $m
	done
	if [ ! -f "$RESULTS" ]
	then
		echo "$names" > "$RESULTS"
	fi
	echo "$means" >> "$RESULTS"
	
	cp -r predictions $blockdir
	
	train_block=$((train_block+1))
done | tee $WD/log
