#!/bin/sh

NTRAIN=100
NTEST=50
TRAIN_CHUNK=10
TRAIN_SEEDS="1 2 3 4 5 6 7 8 9 10"
TEST_SEEDS="101 102 103 104 105 106 107 108 109 110"

WD="data/lc-`date +"%d:%H:%M:%S"`"
mkdir $WD

TRAIN_SCEN="$WD/train_scen"
TEST_SCEN="$WD/test_scen"
RESULTS="$WD/results"

./gen_scenarios2 2 11 $TRAIN_SEEDS | shuf | head -n $NTRAIN >$TRAIN_SCEN
./gen_scenarios2 2 2 $TEST_SEEDS | shuf | head -n $NTEST >$TEST_SCEN

NTRAIN=`wc -l<"$TRAIN_SCEN"`
NTEST=`wc -l<"$TEST_SCEN"`

rm -f models/*

train_block=0

while true
do
	train_start=$((train_block * TRAIN_CHUNK + 1))
	if [ $train_start -gt $NTRAIN ]
	then
		break
	fi

	train_stop=$(((train_block + 1) * TRAIN_CHUNK))
	if [ $train_stop -gt $NTRAIN ]
	then
		train_stop=$NTRAIN
	fi
	
	echo "training on scenarios $train_start - $train_stop"

	rm -f trees/*

	blockdir="$WD/block$train_block"
	mkdir $blockdir
	sed -n -e "${train_start},${train_stop}p" $TRAIN_SCEN > train_batch
	./run_scenarios train train_batch || exit 1
	
	rm -f predictions/*
	./run_scenarios test $TEST_SCEN || exit 1
	
	means=''
	names=''
	# aggregate statistics
	for f in predictions/*.{em,lwr}
	do
		if [ ! -f "$f" ]
		then
			continue
		fi
		n=`basename $f`
		n=${n%.*}
		m=`awk '{print $NF}' $f | tb mean`
		names="$names $n"
		means="$means $m"
		echo $n $m
	done
	if [ ! -f "$RESULTS" ]
	then
		echo "$names" > "$RESULTS"
	fi
	echo "$means" >> "$RESULTS"
	
	cp -r predictions $blockdir
	cp -r models $blockdir
	cp -r trees $blockdir
	
	train_block=$((train_block+1))
done | tee $WD/log
