#!/usr/bin/env python

from __future__ import print_function
import sys, os
import itertools as itl

def usage():
	print('usage: {} num_targets'.format(sys.argv[0]), file=sys.stderr)
	sys.exit(1)

if len(sys.argv) < 2:
	usage()

try:
	ntargets = int(sys.argv[1])
except ValueError:
	usage()

names = ['cur', 'c1'] + ['t{}'.format(i) for i in range(1, ntargets+1)]

preds = [
	('east-of', 2),
	('west-of', 2),
	('north-of', 2),
	('south-of', 2),
	('horizontally-aligned', 2),
	('vertically-aligned', 2),
	('intersect', 2)]

for p, n in preds:
	for params in itl.combinations(names, n):
		print('{} {}'.format(p, ' '.join(params)))
