#!/usr/bin/env python

from __future__ import print_function
import sys, os

rule = '''
sp {{extract
   (state <s> ^superstate nil
              ^svs.command <cmd>)
-->
{}
{}
{}
}}
'''

counter = 0
def ident():
	global counter
	counter += 1
	return '<a{}>'.format(counter)

extracts = []
pred_wmes = []
node_wmes = []
for line in sys.stdin:
	f = line.split()
	pred = f[0]
	param_str = ''
	for i, p in enumerate(f[1:]):
		id = ident()
		param_str += ' ^{} {}'.format(chr(ord('a') + i), id)
		node_wmes.append('({} ^name {} ^type node)'.format(id, p))
	
	id = ident()
	extracts.append(id)
	pred_wmes.append('({} ^type {} {})'.format(id, pred, param_str))

cmd_line = '(<cmd> ' + ' '.join('^extract {}'.format(e) for e in extracts) + ')'
preds = '\n'.join(pred_wmes)
nodes = '\n'.join(node_wmes)

print(rule.format(cmd_line, preds, nodes))
