#!/bin/sh

set -m # for job control

root=../../../../out
export LD_LIBRARY_PATH=$root/lib:$LD_LIBRARY_PATH
soar=$root/cli

remote_args=""
env_args="1 3"               # default seed = 1 and 3 blocks not touching

#export SVS_DATA_PIPE=/tmp/datavis
#export SVS_DISPLAY_PIPE=/tmp/dispfifo

# kill all old jobs first
ps | awk '$4 == "run" && $1 != '"$$"' { system("kill " $1) }'
rm -f env ctrl

run_env() {
	while [ ! -S env ]
	do
		sleep 0.5
	done
	socat unix-connect:env system:"python targets.py $*"
}

run_remote() {
	if [ -z "$1" ]
	then
		return
	fi
	
	while [ ! -p ctrl ]
	do
		sleep 0.5
	done
	
	case "$1" in
	log)
		cat remote.log >ctrl
		return
		;;
	gui)
		python remote.py >ctrl
		return
		;;
	fixed)
		awk -v "nsteps=$2" -v "seed=$3" -v "x=$4" -v "y=$5" '
			BEGIN {
				srand(seed)
				for (i = 0; i < nsteps; ++i) {
					printf("%.3f %.3f\n", x + rand() / 10, y + rand() / 10)
				}
			}' >ctrl
		;;
	*)
		echo "unknown remote argument $1" >&2
		exit 1
	esac
}

while test -n "$1"
do
	case "$1" in
	-g)
		debug=1
		;;
	-gg)
		debug=2
		;;
	-r)
		remote_args="$2"
		shift
		;;
	-e)
		env_args="$2"
		shift
		;;
	-s)
		source="$source -s $2"
		shift
		;;
	*)
		break
		;;
	esac
	shift
done

if [ -z "$source" ]
then
	source="-s agent/planner.soar"
fi

run_env $env_args &
envpid=$!
run_remote $remote_args &
remotepid=$!

case "$debug" in
1)
	gdb --args $soar $source "$@"
	;;
2)
	gdb -ex run -ex quit --args $soar $source "$@" | tee stdout.log
	if grep -q 'exited normally' stdout.log
	then
		soarexit=0
	else
		soarexit=1
	fi
	rm stdout.log
	;;
*)
	$soar $source "$@"
	#echo "$!" > soar.pid
	#fg
	#ltrace -c $soar $agent 2>soar.trace
	soarexit=$?
esac

pyprocs=`ps | awk '$4 == "python" {print $1}'`
if [ -n "$pyprocs" ]
then
	kill $pyprocs
fi

rm -f env ctrl

if [ "$soarexit" -ne 0 ]
then
	kill $envpid
	kill $remotepid
	exit 1
fi
