#!/bin/sh

root=../../../../out
export LD_LIBRARY_PATH=$root/lib:$HOME/local/lib:$LD_LIBRARY_PATH
soar=$root/bin/cli
agent=agent/targets.soar

export SVS_DATA_PIPE=/tmp/datavis
#export SVS_DISPLAY_PIPE=/tmp/dispfifo


# kill all old jobs first
ps | awk '$4 == "run" && $1 != '"$$"' { system("kill " $1) }'

run_env() {
	while [ ! -S env ]
	do
		sleep 1
	done
	socat unix-connect:env exec:'python targets.py'
}

run_remote() {
	while [ ! -p ctrl ]
	do
		sleep 1
	done
	python remote.py
	#cat remote.log >>ctrl
}

while test -n "$1"
do
	case "$1" in
	-g)
		debug=1
		;;
	esac
	shift
done

run_env &
run_remote &

if test "$debug" == "1"
then
	gdb --args $soar $agent
else
	$soar $agent
fi

kill `ps | grep python | awk '{print $1}'`
rm -f env ctrl
