#!/bin/sh

mail_error() {
	f="$(mktemp).tar.gz"
	tar c models | gzip > $f
	mail -s "run_scenarios error" -a "$f" "josephzxu@gmail.com" <<- EOF
	offending command was
	$1
	EOF
	rm "$f"
}

if [ -z "$1" ]
then
	echo choose either train or test >&2
	exit 1
fi

case "$1" in
train)
	export SVS_SAVE_MODELS=1
	unset SVS_LOG_PREDICTION_ERRORS
	;;
test)
	export SVS_LOG_PREDICTION_ERRORS=1
	unset SVS_SAVE_MODELS
	;;
esac

iter=0
OIFS="$IFS"
IFS='
'

for line in `cat $2`
do
	IFS="$OIFS"
	echo iteration $iter
	iter=$((iter+1))
	echo "$line"
	eval "$line"
	exitcode=$?
	if [ $exitcode -ne 0 ]
	then
		# try to drop into a debug session
		if ! echo "$line" | grep -q -- -g
		then
			mail_error "$line"
			line=`echo "$line" | sed 's/run/run -g/'`
			echo Debugging with "$line"
			eval "$line"
		fi
		echo failed with $exitcode >&2
		exit $exitcode
	fi
done
