#!/bin/sh

if [ -z "$1" ]
then
	echo choose either train or test >&2
	exit 1
fi

case "$1" in
train)
	export SVS_SAVE_MODELS=1
	unset SVS_LOG_PREDICTION_ERRORS
	;;
test)
	export SVS_LOG_PREDICTION_ERRORS=1
	unset SVS_SAVE_MODELS
	;;
esac
	

iter=0
while read line
do
	echo iteration $iter
	iter=$((iter+1))
	eval "$line"
	exitcode=$?
	if [ $exitcode -ne 0 ]
	then
		echo failed with $exitcode >&2
		exit $exitcode
	fi
done
