#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#

Import('compEnv')
env = compEnv.Clone()

TestCLI = env.Program('TestCLI', Glob('*.cpp'))
env.Install('$PREFIX/bin', TestCLI)

