#!/usr/bin/python

Import('env')
env = env.Clone()

env.Prepend(CPPPATH = [	'#ClientSML/src',
			'#ElementXML/src',
			'#ConnectionSML/src'])

libadd = [ 'ClientSML', 'ConnectionSML', 'ElementXML', ]
if env['STATIC_LINKED']:
	libadd = [ 'ClientSML', 'ConnectionSML', 'ElementXML', 'SoarKernelSML', 'SoarKernel', 'CommandLineInterface', 'sqlite3' ]

env.Append(LIBS = libadd, LIBPATH = '$PREFIX/lib')

TestCLI = env.Program('TestCLI', Glob('*.cpp'))

env.Install('$PREFIX/bin', TestCLI)

