
#import "kernel/AgentTest.mm"
#import "kernel/AliasTest.mm"
#import "kernel/BasicTests.mm"
#import "kernel/CliParserTest.mm"
#import "kernel/EpMemFunctionalTests.mm"
#import "kernel/FunctionalTests.mm"
#import "kernel/SMemEpMemCombinedFunctionalTests.mm"
#import "kernel/SMemFunctionalTests.mm"
#import "kernel/wma/WmaFunctionalTests.mm"
