
#import "kernel/AgentTest.mm"
#import "kernel/AliasTest.mm"
#import "kernel/BasicTests.mm"
#import "kernel/CliParserTest.mm"
#import "kernel/ElementXMLTest.mm"
#import "kernel/EpMemFunctionalTests.mm"
#import "kernel/FullTests.mm"
#import "kernel/FullTestsClientThread.mm"
#import "kernel/FullTestsClientThreadFullyOptimized.mm"
#import "kernel/FullTestsRemote.mm"
#import "kernel/FunctionalTests.mm"
#import "kernel/SMemEpMemCombinedFunctionalTests.mm"
#import "kernel/SMemFunctionalTests.mm"
#import "kernel/wma/WmaFunctionalTests.mm"
