PARSER_BEGIN(Example)

public class Example {

  public static void main(String args[]) throws ParseException {
    Example parser = new Example(System.in);
    parser.IfStm();
  }

}

PARSER_END(Example)

SKIP :
{
  " "
| "\t"
| "\n"
| "\r"
}

void IfStm() :
{}
{
 "if" C() S() [ "else" S() ]
}

void C() :
{}
{
  "TBD"
}

void S() :
{}
{
  "TBD"
|
  IfStm()
}
