#!/bin/sh
# $Id$

/bin/sh make-clean

pushd kernel
chmod u+x ./configure

CFLAGS="-fno-common -O2 -w" ./configure
if [ $? != "0" ]; then
  echo
  echo "!!! Couldn't configure kernel (check for error messages above)."
  exit
fi

make

if [ $? != "0" ]; then
  exit
fi

popd
pushd tcl-interface
chmod u+x ./configure

CFLAGS="-fno-common -O2 -w" ./configure --disable-static-soartk --disable-static-soar \
--with-tcl-lib-dir=/usr/lib --with-tcl-doc-dir=/Library/Tcl/man

if [ $? != "0" ]; then
  echo
  echo "!!! Couldn't configure tcl-interface (check for error messages above)."
  exit
fi

make

if [ $? != "0" ]; then
  exit
fi

cp  libsoar8.5* ../library
popd

chmod u+x ./init-soar*.tcl

echo
echo "*** You will most likely want to invoke Soar with the wish executable, e.g.:"
echo "*** bash$ wish init-soar-auto-create-agent.tcl"
echo


