#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
Import('env')
FilterC = env.Program('FilterC', Glob('*.cpp'))
env.Install('$OUT_DIR', FilterC)

