#!/usr/bin/python
import sys

Import('env')
env = env.Clone()

env.Prepend(CPPPATH = [	'#ClientSML/include',
			'#ElementXML/include',
			'#ConnectionSML/include'])

libadd = [ 'ClientSML', 
	   'ConnectionSML',
	   'ElementXML', 
	   ]

libpath = [ '$PREFIX/lib' ]

env.Append(LIBS = libadd, LIBPATH = libpath)
FilterC = env.Program('FilterC', Glob('*.cpp'))
env.Install('$PREFIX/bin', FilterC)

