#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
Import('compEnv')
FilterC = compEnv.Program('FilterC', Glob('*.cpp'))
compEnv.Install('$PREFIX/bin', FilterC)

