/* Generated By:JavaCC: Do not edit this line. SoarParserConstants.java */
package edu.umich.visualsoar.parser;

public interface SoarParserConstants {

  int EOF = 0;
  int SP = 7;
  int GP = 8;
  int SOARCMD = 9;
  int RARROW = 16;
  int SAME_TYPE = 17;
  int GEQUAL = 18;
  int LDISJUNCT = 19;
  int LEQUAL = 20;
  int NEQUAL = 21;
  int RDISJUNCT = 22;
  int AMPERSAND = 23;
  int ATSIGN = 24;
  int CARET = 25;
  int COMMA = 26;
  int EMARK = 27;
  int EQUAL = 28;
  int GREATER = 29;
  int HYPHEN = 30;
  int LBRACE = 31;
  int LESS = 32;
  int LPAREN = 33;
  int PERIOD = 34;
  int PLUS = 35;
  int QMARK = 36;
  int RBRACE = 37;
  int RPAREN = 38;
  int TILDE = 39;
  int LSQBRACET = 40;
  int RSQBRACET = 41;
  int QUOTE = 42;
  int PRODTYPE = 43;
  int VARIABLE = 44;
  int INTEGER_CONST = 45;
  int SYMBOLIC_CONST = 46;
  int FLOATING_POINT_CONST = 47;
  int EXPONENT = 48;
  int TCL_PREPROCESS = 49;

  int DEFAULT = 0;
  int IN_SOAR_PRODUCTION = 1;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"sp\"",
    "\"gp\"",
    "<SOARCMD>",
    "<token of kind 10>",
    "<token of kind 11>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"-->\"",
    "\"<=>\"",
    "\">=\"",
    "\"<<\"",
    "\"<=\"",
    "\"<>\"",
    "\">>\"",
    "\"&\"",
    "\"@\"",
    "\"^\"",
    "\",\"",
    "\"!\"",
    "\"=\"",
    "\">\"",
    "\"-\"",
    "\"{\"",
    "\"<\"",
    "\"(\"",
    "\".\"",
    "\"+\"",
    "\"?\"",
    "\"}\"",
    "\")\"",
    "\"~\"",
    "\"[\"",
    "\"]\"",
    "\"\\\"\"",
    "<PRODTYPE>",
    "<VARIABLE>",
    "<INTEGER_CONST>",
    "<SYMBOLIC_CONST>",
    "<FLOATING_POINT_CONST>",
    "<EXPONENT>",
    "<TCL_PREPROCESS>",
  };

}
