#echo off
cd Environments\JavaBaseEnvironment
call build.bat
cd ..\JavaEaters
call build.bat
cd ..\JavaMissionaries
call build.bat
cd ..\JavaTankSoar
call build.bat
cd ..\JavaTOH
call build.bat
cd ..\..\Tools\SoarJavaDebugger
call build.bat
cd ..\TestJavaSML
call build.bat
cd ..\VisualSoar
call build.bat
cd ..\..