#!/usr/bin/python
import glob

Import('env')
env = env.Copy()
env.Prepend(CPPPATH = ['src', 
		       'include', 
		       '../SoarKernel/include', 
		       '../gSKI/src', 
		       '../gSKI/include', 
		       '../ElementXML/include', 
		       '../ConnectionSML/include', 
		       '../KernelSML/include', ])

CommandLineInterface = env.Library('CommandLineInterface', glob.glob('src/*.cpp'))
env.Install('#SoarLibrary/lib', CommandLineInterface)
