#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
Import('env')

if env['SCU']:
	CommandLineInterface = env.Library('CommandLineInterface', 'CommandLineInterface.cxx')
else:
	CommandLineInterface = env.Library('CommandLineInterface', Glob('src/*.cpp'))

env.Install('$PREFIX/lib', CommandLineInterface)

