/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class SystemEventHandlerPlusData extends EventHandlerPlusData {
  private long swigCPtr;

  protected SystemEventHandlerPlusData(long cPtr, boolean cMemoryOwn) {
    super(smlJNI.SWIGSystemEventHandlerPlusDataUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SystemEventHandlerPlusData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected SystemEventHandlerPlusData() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      smlJNI.delete_SystemEventHandlerPlusData(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public void setM_Handler(SWIGTYPE_p_f_enum_sml__smlSystemEventId_p_void_p_sml__Kernel__void m_Handler) {
    smlJNI.set_SystemEventHandlerPlusData_m_Handler(swigCPtr, SWIGTYPE_p_f_enum_sml__smlSystemEventId_p_void_p_sml__Kernel__void.getCPtr(m_Handler));
  }

  public SWIGTYPE_p_f_enum_sml__smlSystemEventId_p_void_p_sml__Kernel__void getM_Handler() {
    long cPtr = smlJNI.get_SystemEventHandlerPlusData_m_Handler(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_enum_sml__smlSystemEventId_p_void_p_sml__Kernel__void(cPtr, false);
  }

  public SystemEventHandlerPlusData(int eventID, SWIGTYPE_p_f_enum_sml__smlSystemEventId_p_void_p_sml__Kernel__void handler, SWIGTYPE_p_void userData, int callbackID) {
    this(smlJNI.new_SystemEventHandlerPlusData(eventID, SWIGTYPE_p_f_enum_sml__smlSystemEventId_p_void_p_sml__Kernel__void.getCPtr(handler), SWIGTYPE_p_void.getCPtr(userData), callbackID), true);
  }

}
