#!/usr/bin/python
import glob
import shutil
import SoarSCons

Import('env')
env = env.Copy()

SoarSCons.SetJavaPaths(env, 'Core/ClientSMLSWIG/Java/sml.jar:SoarLibrary/bin/swt.jar') 

env.Java(target = 'classes', source = 'src')

env.Append(JARCHDIR = 'Environments/JavaTOH/classes')
JavaTOH = env.Jar(target = 'JavaTOH.jar', source = ['classes', 'JarManifest', ])

env.Clean('classes', 'classes')
