#!/bin/csh
pushd kernel
./configure
/usr/bin/gmake
popd
pushd interface
./configure --prefix=../..  --disable-static-soar --disable-static-soartk --enable-dynamic-soar --with-kernel=../kernel
/usr/bin/gmake
cp  libsoar8.3.5.so ../library
popd
