#import os

plugin = Environment()
# Need some extra flags for Darwin's funky library handling
#if os.uname()[0] == 'Darwin':
#  plugin['SHLINKFLAGS'] = '$LINKFLAGS -bundle -flat_namespace -undefined suppress'
plugin.ParseConfig('pkg-config --cflags --libs playercore')
plugin.Append(CPPPATH = '.')
plugin.Append(CFLAGS = '-Wall')
plugin.Append(CCFLAGS = '-Wall')
plugin.SharedLibrary('exampledriver', ['exampledriver.cc'])
