#!/bin/sh

root=../../../../out
export LD_LIBRARY_PATH=$root/lib:$HOME/local/lib:$LD_LIBRARY_PATH
soar=$root/bin/s

while test -n "$1"
do
	case "$1" in
	-g)
		debug=1
		;;
	esac
	shift
done

(sleep 1; socat unix-connect:env exec:doors) &
#envid=`ps | awk '$4 ~ "doors" {print $1}'`

if test "$debug" == "1"
then
	gdb --args $soar agent/robot.soar
else
	$soar agent/robot.soar
fi

#kill $envid
