# Desc: Example plugin makefile
# CVS: $Id: Makefile.example 4226 2007-10-24 19:01:14Z thjc $

all: liblogplugin.so

%.o: %.cc
	$(CXX) -Wall -fpic -g3 `pkg-config --cflags playercore` -c $<

liblogplugin.so: logplugin.o
	$(CXX) -shared -nostartfiles -o $@ $^

clean:
	rm -f *.o *.so
