#!/usr/bin/python
import glob

Import('env')
env = env.Copy()
env.Prepend(CPPPATH = ['src', 'include', '../ElementXML/include',])

ConnectionSML = env.Library('ConnectionSML', glob.glob('src/*.cpp'))
env.Install('#SoarLibrary/lib', ConnectionSML)
