#!/usr/bin/python
import glob

Import('env')
env = env.Clone()
env.Prepend(CPPPATH = ['src', 'include', '../ElementXML/include',])

if env['scu']:
	ConnectionSML = env.Library('ConnectionSML', 'ConnectionSML.cxx')
else:
	ConnectionSML = env.Library('ConnectionSML', glob.glob('src/*.cpp'))

env.Install('#SoarLibrary/lib', ConnectionSML)
