#!/usr/bin/python
import glob
import SoarSCons

Import('env')
env = env.Copy()

SoarSCons.SetJavaPaths(env, 'Core/ClientSMLSWIG/Java/sml.jar:SoarLibrary/bin/swt.jar')

env.Java(target = 'classes', source = 'src')

env.Append(JARCHDIR = 'Tools/TestJavaSML/classes')
TestJavaSML = env.Jar(target = 'TestJavaSML.jar', source = ['classes', 'JarManifest', ])

env.Install('#SoarLibrary/bin', TestJavaSML)

env.Clean('classes', 'classes')
