#!/usr/bin/python
import sys

Import('env')
env = env.Clone()

env.Prepend(CPPPATH = [	'#ClientSML/src',
			'#ElementXML/src',
			'#ConnectionSML/src'])

libadd = [ 'ClientSML', 
	   'ConnectionSML',
	   'ElementXML', 
	   ]

libpath = [ '$PREFIX/lib' ]

env.Append(LIBS = libadd, LIBPATH = libpath)
if env['SCU']:
	QuickLink = env.Program('QuickLink', 'QuickLink.cxx')
else:
	QuickLink = env.Program('QuickLink', Glob('src/*.cpp'))
env.Install('$PREFIX/bin', QuickLink)

