#!/usr/bin/python
import glob
import shutil
import SoarSCons
import sys

Import('env')
env = env.Clone()

if sys.platform == 'cygwin':
	SoarSCons.SetJavaPaths(env, '"Core/ClientSMLSWIG/Java/sml.jar;SoarLibrary/bin/swt.jar"')
else:
	SoarSCons.SetJavaPaths(env, 'Core/ClientSMLSWIG/Java/sml.jar:SoarLibrary/bin/swt.jar')

javacStep = env.Java(target = 'classes', source = 'src')

copySources = glob.glob('src/mac/*')
copyTargets = map(lambda x: x.replace('src', 'classes'), copySources)

copyStep = env.Command(copyTargets, copySources, SoarSCons.DoCopy)
jarStep = env.Command('#Environments/JavaMissionaries/JavaMissionaries.jar', [copySources, 'classes'], 'jar cfm Environments/JavaMissionaries/JavaMissionaries.jar Environments/JavaMissionaries/JarManifest -C Environments/JavaMissionaries/classes .')

env.Depends(jarStep, copyStep)
env.Depends(copyStep, javacStep)

env.Clean('classes', 'classes')
