#!/usr/bin/python

Import('env')
env = env.Clone()

env.Prepend(CPPPATH = [	'#ClientSML/include',
			'#ElementXML/include',
			'#ConnectionSML/include'])

libadd = [ 'ClientSML', 'ConnectionSML', 'ElementXML', ]

env.Append(LIBS = libadd, LIBPATH = '$PREFIX/lib')

TestCLI = env.Program('TestCLI', Glob('*.cpp'))

env.Install('$PREFIX/bin', TestCLI)

