#!/usr/bin/python

import glob
import sys

Import('env')
env = env.Copy()
env.Prepend(CPPPATH = ['src', 
		       'include', 
		       '../SoarKernel/include',
		       '../gSKI/src',
		       '../gSKI/include',
		       '../CLI/include',
		       '../ElementXML/include',
		       '../ConnectionSML/include'])

if sys.platform == 'cygwin':
	env.Append(CPPFLAGS = ' -D_USRDLL')
	env['no_import_lib'] = 1

libadd = [
	   'ElementXML',
	   'ConnectionSML',
	   'CommandLineInterface',
	   'gSKI',
	   'SoarKernel',
	   ]

if sys.platform == 'cygwin':
	   libadd.extend(['pcre',])

if sys.platform == 'cygwin':
	libadd.extend(['ws2_32',])
	 
libpath = [ 
	    '../SoarKernel',
	    '../gSKI',
	    '../CLI',
	    '../ConnectionSML',
	    '../ElementXML', 
	    '../pcre', 
	    ]

if env['static']:
	SoarKernelSMLStatic = env.StaticLibrary('SoarKernelSML', glob.glob('src/*.cpp'), LIBS = libadd, LIBPATH = libpath)
	env.Install('#SoarLibrary/lib', SoarKernelSMLStatic)
else:
	SoarKernelSML = env.SharedLibrary('SoarKernelSML', glob.glob('src/*.cpp'), LIBS = libadd, LIBPATH = libpath)
	env.Install('#SoarLibrary/lib', SoarKernelSML)

