#!/usr/bin/python
import os
import SoarSCons

Import('env')
env = env.Clone()

theJar = '#Environments/Soar2D/Soar2D.jar';
sources = SoarSCons.JavaSources('src')
sources.extend(SoarSCons.JavaSources('test'))

Depends(theJar, '#Core/ClientSMLSWIG/Java/sml.jar')
Depends(theJar, 'build.xml')

env.Command(theJar, sources, 'ant -q', chdir=1)

