#!/usr/bin/python
import glob
import shutil
import SoarSCons

Import('env')
env = env.Copy()

SoarSCons.SetJavaPaths(env, 'Core/ClientSMLSWIG/Java/sml.jar:SoarLibrary/bin/swt.jar:SoarLibrary/bin/tosca.jar:Environments/Soar2D/jdom.jar')

javacStep = env.Java(target = 'classes', source = 'src')

copySources = []
copySources.extend(glob.glob('src/*.xml'))
copySources.extend(glob.glob('src/images/book/*'))
copySources.extend(glob.glob('src/images/tanksoar/*'))

copyTargets = map(lambda x: x.replace('src', 'classes'), copySources)
	
copyStep = env.Command(copyTargets, copySources, SoarSCons.DoCopy)
jarStep = env.Command('#Environments/Soar2D/Soar2D.jar', [copySources, 'classes'], 'jar cfm Environments/Soar2D/Soar2D.jar Environments/Soar2D/JarManifest -C Environments/Soar2D/classes .')

env.Depends(jarStep, copyStep)
env.Depends(copyStep, javacStep)

env.Clean('classes', 'classes')
