#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
Import('env')
TestSMLEvents = env.Program('TestSMLEvents', Glob('*.cpp'))
env.Alias('TestSMLEvents', env.Install('$OUT_DIR', TestSMLEvents))

