#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#

Import('compEnv')
env = compEnv.Clone()

TestSMLEvents = env.Program('TestSMLEvents', Glob('*.cpp'))
Install('$PREFIX/bin', TestSMLEvents)

