/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sourceforge.playerstage.Jplayercore;

public class player_msghdr_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected player_msghdr_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(player_msghdr_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      playercore_javaJNI.delete_player_msghdr_t(swigCPtr);
    }
    swigCPtr = 0;
  }

  protected static long[] cArrayUnwrap(player_msghdr_t[] arrayWrapper) {
      long[] cArray = new long[arrayWrapper.length];
      for (int i=0; i<arrayWrapper.length; i++)
        cArray[i] = player_msghdr_t.getCPtr(arrayWrapper[i]);
      return cArray;
  }

  protected static player_msghdr_t[] cArrayWrap(long[] cArray, boolean cMemoryOwn) {
    player_msghdr_t[] arrayWrapper = new player_msghdr_t[cArray.length];
    for (int i=0; i<cArray.length; i++)
      arrayWrapper[i] = new player_msghdr_t(cArray[i], cMemoryOwn);
    return arrayWrapper;
  }

  public void setAddr(player_devaddr_t value) {
    playercore_javaJNI.player_msghdr_t_addr_set(swigCPtr, this, player_devaddr_t.getCPtr(value), value);
  }

  public player_devaddr_t getAddr() {
    long cPtr = playercore_javaJNI.player_msghdr_t_addr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new player_devaddr_t(cPtr, false);
  }

  public void setType(short value) {
    playercore_javaJNI.player_msghdr_t_type_set(swigCPtr, this, value);
  }

  public short getType() {
    return playercore_javaJNI.player_msghdr_t_type_get(swigCPtr, this);
  }

  public void setSubtype(short value) {
    playercore_javaJNI.player_msghdr_t_subtype_set(swigCPtr, this, value);
  }

  public short getSubtype() {
    return playercore_javaJNI.player_msghdr_t_subtype_get(swigCPtr, this);
  }

  public void setTimestamp(double value) {
    playercore_javaJNI.player_msghdr_t_timestamp_set(swigCPtr, this, value);
  }

  public double getTimestamp() {
    return playercore_javaJNI.player_msghdr_t_timestamp_get(swigCPtr, this);
  }

  public void setSeq(long value) {
    playercore_javaJNI.player_msghdr_t_seq_set(swigCPtr, this, value);
  }

  public long getSeq() {
    return playercore_javaJNI.player_msghdr_t_seq_get(swigCPtr, this);
  }

  public void setSize(long value) {
    playercore_javaJNI.player_msghdr_t_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return playercore_javaJNI.player_msghdr_t_size_get(swigCPtr, this);
  }

  public player_msghdr_t() {
    this(playercore_javaJNI.new_player_msghdr_t(), true);
  }

}
