/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sourceforge.playerstage.Jplayercore;

public class player_orientation_3d_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected player_orientation_3d_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(player_orientation_3d_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      playercore_javaJNI.delete_player_orientation_3d_t(swigCPtr);
    }
    swigCPtr = 0;
  }

  protected static long[] cArrayUnwrap(player_orientation_3d_t[] arrayWrapper) {
      long[] cArray = new long[arrayWrapper.length];
      for (int i=0; i<arrayWrapper.length; i++)
        cArray[i] = player_orientation_3d_t.getCPtr(arrayWrapper[i]);
      return cArray;
  }

  protected static player_orientation_3d_t[] cArrayWrap(long[] cArray, boolean cMemoryOwn) {
    player_orientation_3d_t[] arrayWrapper = new player_orientation_3d_t[cArray.length];
    for (int i=0; i<cArray.length; i++)
      arrayWrapper[i] = new player_orientation_3d_t(cArray[i], cMemoryOwn);
    return arrayWrapper;
  }

  public void setProll(double value) {
    playercore_javaJNI.player_orientation_3d_t_proll_set(swigCPtr, this, value);
  }

  public double getProll() {
    return playercore_javaJNI.player_orientation_3d_t_proll_get(swigCPtr, this);
  }

  public void setPpitch(double value) {
    playercore_javaJNI.player_orientation_3d_t_ppitch_set(swigCPtr, this, value);
  }

  public double getPpitch() {
    return playercore_javaJNI.player_orientation_3d_t_ppitch_get(swigCPtr, this);
  }

  public void setPyaw(double value) {
    playercore_javaJNI.player_orientation_3d_t_pyaw_set(swigCPtr, this, value);
  }

  public double getPyaw() {
    return playercore_javaJNI.player_orientation_3d_t_pyaw_get(swigCPtr, this);
  }

  public player_orientation_3d_t() {
    this(playercore_javaJNI.new_player_orientation_3d_t(), true);
  }

}
