/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sourceforge.playerstage.Jplayercore;

public class QueuePointer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected QueuePointer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QueuePointer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      playercore_javaJNI.delete_QueuePointer(swigCPtr);
    }
    swigCPtr = 0;
  }

  public QueuePointer() {
    this(playercore_javaJNI.new_QueuePointer__SWIG_0(), true);
  }

  public QueuePointer(boolean _Replace, long _Maxlen) {
    this(playercore_javaJNI.new_QueuePointer__SWIG_1(_Replace, _Maxlen), true);
  }

  public QueuePointer(QueuePointer CopyFrom) {
    this(playercore_javaJNI.new_QueuePointer__SWIG_2(QueuePointer.getCPtr(CopyFrom), CopyFrom), true);
  }

  public MessageQueue __deref__() {
    long cPtr = playercore_javaJNI.QueuePointer___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new MessageQueue(cPtr, false);
  }

  public MessageQueue get() {
    long cPtr = playercore_javaJNI.QueuePointer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MessageQueue(cPtr, false);
  }

  public MessageQueue __ref__() {
    return new MessageQueue(playercore_javaJNI.QueuePointer___ref__(swigCPtr, this), false);
  }

  public boolean Empty() {
    return playercore_javaJNI.QueuePointer_Empty(swigCPtr, this);
  }

  public boolean Push(Message msg) {
    return playercore_javaJNI.QueuePointer_Push(swigCPtr, this, Message.getCPtr(msg), msg);
  }

  public void PushFront(Message msg, boolean haveLock) {
    playercore_javaJNI.QueuePointer_PushFront(swigCPtr, this, Message.getCPtr(msg), msg, haveLock);
  }

  public void PushBack(Message msg, boolean haveLock) {
    playercore_javaJNI.QueuePointer_PushBack(swigCPtr, this, Message.getCPtr(msg), msg, haveLock);
  }

  public Message Pop() {
    long cPtr = playercore_javaJNI.QueuePointer_Pop(swigCPtr, this);
    return (cPtr == 0) ? null : new Message(cPtr, false);
  }

  public void SetReplace(boolean _Replace) {
    playercore_javaJNI.QueuePointer_SetReplace(swigCPtr, this, _Replace);
  }

  public void AddReplaceRule(int _host, int _robot, int _interf, int _index, int _type, int _subtype, int _replace) {
    playercore_javaJNI.QueuePointer_AddReplaceRule__SWIG_0(swigCPtr, this, _host, _robot, _interf, _index, _type, _subtype, _replace);
  }

  public void AddReplaceRule(player_devaddr_t device, int _type, int _subtype, int _replace) {
    playercore_javaJNI.QueuePointer_AddReplaceRule__SWIG_1(swigCPtr, this, player_devaddr_t.getCPtr(device), device, _type, _subtype, _replace);
  }

  public int CheckReplace(player_msghdr_t hdr) {
    return playercore_javaJNI.QueuePointer_CheckReplace(swigCPtr, this, player_msghdr_t.getCPtr(hdr), hdr);
  }

  public boolean Wait(double TimeOut) {
    return playercore_javaJNI.QueuePointer_Wait__SWIG_0(swigCPtr, this, TimeOut);
  }

  public boolean Wait() {
    return playercore_javaJNI.QueuePointer_Wait__SWIG_1(swigCPtr, this);
  }

  public void DataAvailable() {
    playercore_javaJNI.QueuePointer_DataAvailable(swigCPtr, this);
  }

  public boolean Filter(Message msg) {
    return playercore_javaJNI.QueuePointer_Filter(swigCPtr, this, Message.getCPtr(msg), msg);
  }

  public void ClearFilter() {
    playercore_javaJNI.QueuePointer_ClearFilter(swigCPtr, this);
  }

  public void SetFilter(int host, int robot, int interf, int index, int type, int subtype) {
    playercore_javaJNI.QueuePointer_SetFilter(swigCPtr, this, host, robot, interf, index, type, subtype);
  }

  public void SetPull(boolean _pull) {
    playercore_javaJNI.QueuePointer_SetPull(swigCPtr, this, _pull);
  }

  public long GetLength() {
    return playercore_javaJNI.QueuePointer_GetLength(swigCPtr, this);
  }

  public void SetDataRequested(boolean d, boolean haveLock) {
    playercore_javaJNI.QueuePointer_SetDataRequested(swigCPtr, this, d, haveLock);
  }

}
