/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sourceforge.playerstage.Jplayertcp;

public class PlayerTCP {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PlayerTCP(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PlayerTCP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      playertcp_javaJNI.delete_PlayerTCP(swigCPtr);
    }
    swigCPtr = 0;
  }

  public PlayerTCP() {
    this(playertcp_javaJNI.new_PlayerTCP(), true);
  }

  public void Lock() {
    playertcp_javaJNI.PlayerTCP_Lock(swigCPtr, this);
  }

  public void Unlock() {
    playertcp_javaJNI.PlayerTCP_Unlock(swigCPtr, this);
  }

  public static void InitGlobals() {
    playertcp_javaJNI.PlayerTCP_InitGlobals();
  }

  public void setThread(SWIGTYPE_p_pthread_t value) {
    playertcp_javaJNI.PlayerTCP_thread_set(swigCPtr, this, SWIGTYPE_p_pthread_t.getCPtr(value));
  }

  public SWIGTYPE_p_pthread_t getThread() {
    return new SWIGTYPE_p_pthread_t(playertcp_javaJNI.PlayerTCP_thread_get(swigCPtr, this), true);
  }

  public int Listen(int[] ports, int num_ports, int[] new_ports) {
    return playertcp_javaJNI.PlayerTCP_Listen__SWIG_0(swigCPtr, this, ports, num_ports, new_ports);
  }

  public int Listen(int[] ports, int num_ports) {
    return playertcp_javaJNI.PlayerTCP_Listen__SWIG_1(swigCPtr, this, ports, num_ports);
  }

  public int Listen(int port) {
    return playertcp_javaJNI.PlayerTCP_Listen__SWIG_2(swigCPtr, this, port);
  }

  public SWIGTYPE_p_QueuePointer AddClient(SWIGTYPE_p_sockaddr_in cliaddr, long local_host, long local_port, int newsock, boolean send_banner, int[] kill_flag, boolean have_lock) {
    return new SWIGTYPE_p_QueuePointer(playertcp_javaJNI.PlayerTCP_AddClient(swigCPtr, this, SWIGTYPE_p_sockaddr_in.getCPtr(cliaddr), local_host, local_port, newsock, send_banner, kill_flag, have_lock), true);
  }

  public int Update(int timeout) {
    return playertcp_javaJNI.PlayerTCP_Update(swigCPtr, this, timeout);
  }

  public int Accept(int timeout) {
    return playertcp_javaJNI.PlayerTCP_Accept(swigCPtr, this, timeout);
  }

  public void Close(int cli) {
    playertcp_javaJNI.PlayerTCP_Close(swigCPtr, this, cli);
  }

  public int ReadClient(int cli) {
    return playertcp_javaJNI.PlayerTCP_ReadClient__SWIG_0(swigCPtr, this, cli);
  }

  public int ReadClient(SWIGTYPE_p_QueuePointer q) {
    return playertcp_javaJNI.PlayerTCP_ReadClient__SWIG_1(swigCPtr, this, SWIGTYPE_p_QueuePointer.getCPtr(q));
  }

  public int Read(int timeout, boolean have_lock) {
    return playertcp_javaJNI.PlayerTCP_Read(swigCPtr, this, timeout, have_lock);
  }

  public int Write(boolean have_lock) {
    return playertcp_javaJNI.PlayerTCP_Write(swigCPtr, this, have_lock);
  }

  public int WriteClient(int cli) {
    return playertcp_javaJNI.PlayerTCP_WriteClient(swigCPtr, this, cli);
  }

  public void DeleteClients() {
    playertcp_javaJNI.PlayerTCP_DeleteClients(swigCPtr, this);
  }

  public void ParseBuffer(int cli) {
    playertcp_javaJNI.PlayerTCP_ParseBuffer(swigCPtr, this, cli);
  }

  public int HandlePlayerMessage(int cli, SWIGTYPE_p_Message msg) {
    return playertcp_javaJNI.PlayerTCP_HandlePlayerMessage(swigCPtr, this, cli, SWIGTYPE_p_Message.getCPtr(msg));
  }

  public void DeleteClient(SWIGTYPE_p_QueuePointer q, boolean have_lock) {
    playertcp_javaJNI.PlayerTCP_DeleteClient(swigCPtr, this, SWIGTYPE_p_QueuePointer.getCPtr(q), have_lock);
  }

  public boolean Listening(int port) {
    return playertcp_javaJNI.PlayerTCP_Listening(swigCPtr, this, port);
  }

  public SWIGTYPE_p_uint32_t GetHost() {
    return new SWIGTYPE_p_uint32_t(playertcp_javaJNI.PlayerTCP_GetHost(swigCPtr, this), true);
  }

}
