/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sourceforge.playerstage.Jplayertcp;

public class playertcp_java implements playertcp_javaConstants {
  public static SWIGTYPE_p_f_p_void_size_t_p_void_int__int playerxdr_get_packfunc(SWIGTYPE_p_uint16_t interf, SWIGTYPE_p_uint8_t type, SWIGTYPE_p_uint8_t subtype) {
    long cPtr = playertcp_javaJNI.playerxdr_get_packfunc(SWIGTYPE_p_uint16_t.getCPtr(interf), SWIGTYPE_p_uint8_t.getCPtr(type), SWIGTYPE_p_uint8_t.getCPtr(subtype));
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_size_t_p_void_int__int(cPtr, false);
  }

  public static SWIGTYPE_p_f_p_void_p_q_const__void__unsigned_int playerxdr_get_copyfunc(SWIGTYPE_p_uint16_t interf, SWIGTYPE_p_uint8_t type, SWIGTYPE_p_uint8_t subtype) {
    long cPtr = playertcp_javaJNI.playerxdr_get_copyfunc(SWIGTYPE_p_uint16_t.getCPtr(interf), SWIGTYPE_p_uint8_t.getCPtr(type), SWIGTYPE_p_uint8_t.getCPtr(subtype));
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_q_const__void__unsigned_int(cPtr, false);
  }

  public static SWIGTYPE_p_f_p_void__void playerxdr_get_cleanupfunc(SWIGTYPE_p_uint16_t interf, SWIGTYPE_p_uint8_t type, SWIGTYPE_p_uint8_t subtype) {
    long cPtr = playertcp_javaJNI.playerxdr_get_cleanupfunc(SWIGTYPE_p_uint16_t.getCPtr(interf), SWIGTYPE_p_uint8_t.getCPtr(type), SWIGTYPE_p_uint8_t.getCPtr(subtype));
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__void(cPtr, false);
  }

  public static SWIGTYPE_p_f_p_void__p_void playerxdr_get_clonefunc(SWIGTYPE_p_uint16_t interf, SWIGTYPE_p_uint8_t type, SWIGTYPE_p_uint8_t subtype) {
    long cPtr = playertcp_javaJNI.playerxdr_get_clonefunc(SWIGTYPE_p_uint16_t.getCPtr(interf), SWIGTYPE_p_uint8_t.getCPtr(type), SWIGTYPE_p_uint8_t.getCPtr(subtype));
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__p_void(cPtr, false);
  }

  public static SWIGTYPE_p_f_p_void__void playerxdr_get_freefunc(SWIGTYPE_p_uint16_t interf, SWIGTYPE_p_uint8_t type, SWIGTYPE_p_uint8_t subtype) {
    long cPtr = playertcp_javaJNI.playerxdr_get_freefunc(SWIGTYPE_p_uint16_t.getCPtr(interf), SWIGTYPE_p_uint8_t.getCPtr(type), SWIGTYPE_p_uint8_t.getCPtr(subtype));
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__void(cPtr, false);
  }

  public static SWIGTYPE_p_f_p_void__unsigned_int playerxdr_get_sizeoffunc(SWIGTYPE_p_uint16_t interf, SWIGTYPE_p_uint8_t type, SWIGTYPE_p_uint8_t subtype) {
    long cPtr = playertcp_javaJNI.playerxdr_get_sizeoffunc(SWIGTYPE_p_uint16_t.getCPtr(interf), SWIGTYPE_p_uint8_t.getCPtr(type), SWIGTYPE_p_uint8_t.getCPtr(subtype));
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__unsigned_int(cPtr, false);
  }

  public static int playerxdr_ftable_add(playerxdr_function_t f, int replace) {
    return playertcp_javaJNI.playerxdr_ftable_add(playerxdr_function_t.getCPtr(f), f, replace);
  }

  public static int playerxdr_ftable_add_multi(playerxdr_function_t flist, int replace) {
    return playertcp_javaJNI.playerxdr_ftable_add_multi(playerxdr_function_t.getCPtr(flist), flist, replace);
  }

  public static void playerxdr_ftable_init() {
    playertcp_javaJNI.playerxdr_ftable_init();
  }

  public static long playerxdr_deepcopy_message(SWIGTYPE_p_void src, SWIGTYPE_p_void dest, SWIGTYPE_p_uint16_t interf, SWIGTYPE_p_uint8_t type, SWIGTYPE_p_uint8_t subtype) {
    return playertcp_javaJNI.playerxdr_deepcopy_message(SWIGTYPE_p_void.getCPtr(src), SWIGTYPE_p_void.getCPtr(dest), SWIGTYPE_p_uint16_t.getCPtr(interf), SWIGTYPE_p_uint8_t.getCPtr(type), SWIGTYPE_p_uint8_t.getCPtr(subtype));
  }

  public static SWIGTYPE_p_void playerxdr_clone_message(SWIGTYPE_p_void msg, SWIGTYPE_p_uint16_t interf, SWIGTYPE_p_uint8_t type, SWIGTYPE_p_uint8_t subtype) {
    long cPtr = playertcp_javaJNI.playerxdr_clone_message(SWIGTYPE_p_void.getCPtr(msg), SWIGTYPE_p_uint16_t.getCPtr(interf), SWIGTYPE_p_uint8_t.getCPtr(type), SWIGTYPE_p_uint8_t.getCPtr(subtype));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void playerxdr_free_message(SWIGTYPE_p_void msg, SWIGTYPE_p_uint16_t interf, SWIGTYPE_p_uint8_t type, SWIGTYPE_p_uint8_t subtype) {
    playertcp_javaJNI.playerxdr_free_message(SWIGTYPE_p_void.getCPtr(msg), SWIGTYPE_p_uint16_t.getCPtr(interf), SWIGTYPE_p_uint8_t.getCPtr(type), SWIGTYPE_p_uint8_t.getCPtr(subtype));
  }

  public static void playerxdr_cleanup_message(SWIGTYPE_p_void msg, SWIGTYPE_p_uint16_t interf, SWIGTYPE_p_uint8_t type, SWIGTYPE_p_uint8_t subtype) {
    playertcp_javaJNI.playerxdr_cleanup_message(SWIGTYPE_p_void.getCPtr(msg), SWIGTYPE_p_uint16_t.getCPtr(interf), SWIGTYPE_p_uint8_t.getCPtr(type), SWIGTYPE_p_uint8_t.getCPtr(subtype));
  }

}
