/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sourceforge.playerstage.Jplayertcp;

public interface playertcp_javaConstants {
  public final static int PLAYERTCP_DEFAULT_PORT = playertcp_javaJNI.PLAYERTCP_DEFAULT_PORT_get();
  public final static int PLAYERTCP_READBUFFER_SIZE = playertcp_javaJNI.PLAYERTCP_READBUFFER_SIZE_get();
  public final static int PLAYERTCP_WRITEBUFFER_SIZE = playertcp_javaJNI.PLAYERTCP_WRITEBUFFER_SIZE_get();
}
