#!/usr/bin/python
import os
import SoarSCons

Import('env')
env = env.Clone()

theJar = '#Tools/LoggerJava/LoggerJava.jar';
sources = SoarSCons.JavaSources('src')

Depends(theJar, '#Core/ClientSMLSWIG/Java/sml.jar')
Depends(theJar, 'build.xml')

env.Command(theJar, sources, 'ant -q', chdir=1)

