.PHONY: all clean

all:
	g++ -o UrbanCombatInterface.o -c UrbanCombatInterface.cpp
	g++ -o UrbanCombatEffector.o -c UrbanCombatEffector.cpp
	g++ -o UrbanCombatPercepts.o -c UrbanCombatPercepts.cpp

clean:
	rm -f *.o
