#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
# The presence of this file triggers the build for the python SWIG interface.

Import('compEnv')
compEnv.Install('$PREFIX/bin', 'PythonCLI.py')
compEnv.Install('$PREFIX/bin', 'SoarObfuscator.py')
compEnv.Install('$PREFIX/bin', 'TestPythonSML.py')

