#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Alex Turner <alexlt@umich.edu>

import os, sys
Import('env', 'InstallDir')

settings_install = env.Install(env['OUT_DIR'], 'settings.soar')

all_script_targets = settings_install
if os.name == 'nt':
    jd_install = env.Install(env['OUT_DIR'], 'SoarJavaDebugger.bat')
else:
    jd_install = env.Install(env['OUT_DIR'], 'SoarJavaDebugger.sh')

all_script_targets += jd_install

env.Alias('scripts', all_script_targets)

