#!/bin/csh
pushd kernel
chmod u+x ./configure

# a more verbose version, if everything isn't automatically found...
#./configure --with-tcl-lib-dir=/usr/local/lib --with-tk-lib-dir=/usr/local/lib

./configure

make
popd
pushd tcl-interface
chmod u+x ./configure

# a more verbose version, if everything isn't automatically found...
#./configure --prefix=../.. --with-tcl-lib-dir=/usr/local/lib --with-tcl-doc-dir=/usr/tcl/man --with-tk-lib-dir=/usr/local/lib  --with-kernel=../kernel

./configure --with-preferred-tcl-version=8.3 --with-preferred-tk-version=8.3

make
cp  libsoar8.4* ../library
popd
