#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
Import('compEnv')

if compEnv['STATIC_LINKED']:
	print "Skipping TestExternalLibraryLib due to static linkage"
else:
	TestExternalLibraryLib = compEnv.Program('TestExternalLibraryLib', Glob('*.cpp'))
	compEnv.Install('$PREFIX/bin', TestExternalLibraryLib)

