#!/usr/bin/python

Import('compEnv')
env = compEnv.Clone()

if env['STATIC_LINKED']:
	print "Skipping TestExternalLibraryLib due to static linkage"
else:
	TestExternalLibraryLib = env.SharedLibrary('TestExternalLibraryLib', Glob('*.cpp'))
	env.Install('$PREFIX/lib', TestExternalLibraryLib)

