#!/usr/bin/python

Import('env')
env = env.Clone()

env.Prepend(CPPPATH = ['src', 'include',])

if env['SCU']:
	ElementXML = env.SharedLibrary('ElementXML', 'ElementXML.cxx')
else:
	ElementXML = env.SharedLibrary('ElementXML', Glob('src/*.cpp'))

env.Install('$PREFIX/lib', ElementXML)

