#!/usr/bin/python

Import('env')
env = env.Clone()

env.Prepend(CPPPATH = ['src',])

if env['SCU']:
	if env['STATIC_LINKED']:
		ElementXML = env.Library('ElementXML', 'ElementXML.cxx')
	else:
		ElementXML = env.SharedLibrary('ElementXML', 'ElementXML.cxx')
else:
	if env['STATIC_LINKED']:
		ElementXML = env.Library('ElementXML', Glob('src/*.cpp'))
	else:
		ElementXML = env.SharedLibrary('ElementXML', Glob('src/*.cpp'))

env.Install('$PREFIX/lib', ElementXML)

