#!/usr/bin/python
import glob
import shutil
import SoarSCons
import sys

Import('env')
env = env.Clone()

if sys.platform == 'cygwin':
    SoarSCons.SetJavaPaths(env, '"Core/ClientSMLSWIG/Java/sml.jar;SoarLibrary/bin/swt.jar;SoarLibrary/bin/jcommon-1.0.10.jar;SoarLibrary/bin/jfreechart-1.0.6.jar;SoarLibrary/bin/jfreechart-1.0.6-swt.jar;SoarLibrary/bin/swtgraphics2d.jar"')
else:
    SoarSCons.SetJavaPaths(env, 'Core/ClientSMLSWIG/Java/sml.jar:SoarLibrary/bin/swt.jar:SoarLibrary/bin/jcommon-1.0.10.jar:SoarLibrary/bin/jfreechart-1.0.6.jar:SoarLibrary/bin/jfreechart-1.0.6-swt.jar:SoarLibrary/bin/swtgraphics2d.jar')

javacStep = env.Java(target = 'classes', source = 'src')

copySources = [
	       'src/default-text-9_0_0.dlf',
	       'src/default-layout-9_0_0.dlf',
	      ]
copySources.extend(glob.glob('src/images/*'))
copySources.extend(glob.glob('src/altimages/*'))

copyTargets = map(lambda x: 'classes/' + x.lstrip('src/'), copySources)

copyStep = env.Command(copyTargets, copySources, SoarSCons.DoCopy)
jarStep = env.Command('#Tools/SoarJavaDebugger/SoarJavaDebugger.jar', [copySources, 'classes'], 'jar cfm Tools/SoarJavaDebugger/SoarJavaDebugger.jar Tools/SoarJavaDebugger/JarManifest -C Tools/SoarJavaDebugger/classes .')

env.Depends(jarStep, copyStep)
env.Depends(copyStep, javacStep)

env.Install('#SoarLibrary/bin', '#Tools/SoarJavaDebugger/SoarJavaDebugger.jar')

env.Clean('classes', 'classes')
