#!/usr/bin/perl

$options = "tempOptions";
$template = "soarBuildOptions.tmp";
$header = "soarBuildOptions.h";

open( TMPL, "<$template" ) or die "Can't open template\n";
open( HEADER, ">$header" ) or die "Can't open output file\n";
open( OPTIONS, "<$options" ) or die "Can't open options file\n";

$optsIncluded = 0;
while( <TMPL> ) {

    print HEADER $_;
    
    if ( /Define the Build Here/ && !$optsIncluded ) {
	
	
	while( <OPTIONS> ) {
	    print HEADER "#define $_";
	}
	$optsIncluded = 1;
	close (OPTIONS);
#	`rm -f $options`
    }
}

close( TMPL );
close (HEADER );




