/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sourceforge.playerstage.Jplayercore;

public class Device {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Device(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Device obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      playercore_javaJNI.delete_Device(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Device(player_devaddr_t addr, Driver driver) {
    this(playercore_javaJNI.new_Device(player_devaddr_t.getCPtr(addr), addr, Driver.getCPtr(driver), driver), true);
  }

  public int Subscribe(QueuePointer sub_queue) {
    return playercore_javaJNI.Device_Subscribe(swigCPtr, this, QueuePointer.getCPtr(sub_queue), sub_queue);
  }

  public int Unsubscribe(QueuePointer sub_queue) {
    return playercore_javaJNI.Device_Unsubscribe(swigCPtr, this, QueuePointer.getCPtr(sub_queue), sub_queue);
  }

  public void PutMsg(QueuePointer resp_queue, short type, short subtype, SWIGTYPE_p_void src, long deprecated, SWIGTYPE_p_double timestamp) {
    playercore_javaJNI.Device_PutMsg__SWIG_0(swigCPtr, this, QueuePointer.getCPtr(resp_queue), resp_queue, type, subtype, SWIGTYPE_p_void.getCPtr(src), deprecated, SWIGTYPE_p_double.getCPtr(timestamp));
  }

  public void PutMsg(QueuePointer resp_queue, player_msghdr_t hdr, SWIGTYPE_p_void src, boolean copy) {
    playercore_javaJNI.Device_PutMsg__SWIG_1(swigCPtr, this, QueuePointer.getCPtr(resp_queue), resp_queue, player_msghdr_t.getCPtr(hdr), hdr, SWIGTYPE_p_void.getCPtr(src), copy);
  }

  public void PutMsg(QueuePointer resp_queue, player_msghdr_t hdr, SWIGTYPE_p_void src) {
    playercore_javaJNI.Device_PutMsg__SWIG_2(swigCPtr, this, QueuePointer.getCPtr(resp_queue), resp_queue, player_msghdr_t.getCPtr(hdr), hdr, SWIGTYPE_p_void.getCPtr(src));
  }

  public Message Request(QueuePointer resp_queue, short type, short subtype, SWIGTYPE_p_void src, long deprecated, SWIGTYPE_p_double timestamp, boolean threaded) {
    long cPtr = playercore_javaJNI.Device_Request__SWIG_0(swigCPtr, this, QueuePointer.getCPtr(resp_queue), resp_queue, type, subtype, SWIGTYPE_p_void.getCPtr(src), deprecated, SWIGTYPE_p_double.getCPtr(timestamp), threaded);
    return (cPtr == 0) ? null : new Message(cPtr, false);
  }

  public Message Request(QueuePointer resp_queue, short type, short subtype, SWIGTYPE_p_void src, long deprecated, SWIGTYPE_p_double timestamp) {
    long cPtr = playercore_javaJNI.Device_Request__SWIG_1(swigCPtr, this, QueuePointer.getCPtr(resp_queue), resp_queue, type, subtype, SWIGTYPE_p_void.getCPtr(src), deprecated, SWIGTYPE_p_double.getCPtr(timestamp));
    return (cPtr == 0) ? null : new Message(cPtr, false);
  }

  public static boolean MatchDeviceAddress(player_devaddr_t addr1, player_devaddr_t addr2) {
    return playercore_javaJNI.Device_MatchDeviceAddress(player_devaddr_t.getCPtr(addr1), addr1, player_devaddr_t.getCPtr(addr2), addr2);
  }

  public void setNext(Device value) {
    playercore_javaJNI.Device_next_set(swigCPtr, this, Device.getCPtr(value), value);
  }

  public Device getNext() {
    long cPtr = playercore_javaJNI.Device_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Device(cPtr, false);
  }

  public void setAddr(player_devaddr_t value) {
    playercore_javaJNI.Device_addr_set(swigCPtr, this, player_devaddr_t.getCPtr(value), value);
  }

  public player_devaddr_t getAddr() {
    long cPtr = playercore_javaJNI.Device_addr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new player_devaddr_t(cPtr, false);
  }

  public void setDrivername(String value) {
    playercore_javaJNI.Device_drivername_set(swigCPtr, this, value);
  }

  public String getDrivername() {
    return playercore_javaJNI.Device_drivername_get(swigCPtr, this);
  }

  public void setDriver(Driver value) {
    playercore_javaJNI.Device_driver_set(swigCPtr, this, Driver.getCPtr(value), value);
  }

  public Driver getDriver() {
    long cPtr = playercore_javaJNI.Device_driver_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Driver(cPtr, false);
  }

  public void setInQueue(QueuePointer value) {
    playercore_javaJNI.Device_InQueue_set(swigCPtr, this, QueuePointer.getCPtr(value), value);
  }

  public QueuePointer getInQueue() {
    long cPtr = playercore_javaJNI.Device_InQueue_get(swigCPtr, this);
    return (cPtr == 0) ? null : new QueuePointer(cPtr, false);
  }

  public void setQueues(QueuePointer value) {
    playercore_javaJNI.Device_queues_set(swigCPtr, this, QueuePointer.getCPtr(value), value);
  }

  public QueuePointer getQueues() {
    long cPtr = playercore_javaJNI.Device_queues_get(swigCPtr, this);
    return (cPtr == 0) ? null : new QueuePointer(cPtr, false);
  }

  public void setLen_queues(long value) {
    playercore_javaJNI.Device_len_queues_set(swigCPtr, this, value);
  }

  public long getLen_queues() {
    return playercore_javaJNI.Device_len_queues_get(swigCPtr, this);
  }

}
