/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sourceforge.playerstage.Jplayercore;

class playercore_javaJNI {
  public final static native int hostname_to_packedaddr(long[] jarg1, String jarg2);
  public final static native long new_ConfigFile__SWIG_0(long jarg1, long jarg2);
  public final static native long new_ConfigFile__SWIG_1(String jarg1, long jarg2);
  public final static native long new_ConfigFile__SWIG_2();
  public final static native void delete_ConfigFile(long jarg1);
  public final static native boolean ConfigFile_Load(long jarg1, ConfigFile jarg1_, String jarg2);
  public final static native void ConfigFile_InsertFieldValue(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3, String jarg4);
  public final static native boolean ConfigFile_WarnUnused(long jarg1, ConfigFile jarg1_);
  public final static native boolean ConfigFile_ReadBool(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3, boolean jarg4);
  public final static native String ConfigFile_ReadString(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3, String jarg4);
  public final static native int ConfigFile_ReadInt(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3, int jarg4);
  public final static native double ConfigFile_ReadFloat(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3, double jarg4);
  public final static native double ConfigFile_ReadLength(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3, double jarg4);
  public final static native double ConfigFile_ReadAngle(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3, double jarg4);
  public final static native long ConfigFile_ReadColor(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3, long jarg4);
  public final static native String ConfigFile_ReadFilename(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3, String jarg4);
  public final static native int ConfigFile_GetTupleCount(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3);
  public final static native String ConfigFile_ReadTupleString(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3, int jarg4, String jarg5);
  public final static native int ConfigFile_ReadTupleInt(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3, int jarg4, int jarg5);
  public final static native double ConfigFile_ReadTupleFloat(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3, int jarg4, double jarg5);
  public final static native double ConfigFile_ReadTupleLength(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3, int jarg4, double jarg5);
  public final static native double ConfigFile_ReadTupleAngle(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3, int jarg4, double jarg5);
  public final static native long ConfigFile_ReadTupleColor(long jarg1, ConfigFile jarg1_, int jarg2, String jarg3, int jarg4, long jarg5);
  public final static native int ConfigFile_ReadDeviceAddr(long jarg1, ConfigFile jarg1_, long jarg2, player_devaddr_t jarg2_, int jarg3, String jarg4, int jarg5, int jarg6, String jarg7);
  public final static native boolean ConfigFile_ParseDriver(long jarg1, ConfigFile jarg1_, int jarg2);
  public final static native boolean ConfigFile_ParseInterface(long jarg1, ConfigFile jarg1_, int jarg2);
  public final static native boolean ConfigFile_ParseAllDrivers(long jarg1, ConfigFile jarg1_);
  public final static native boolean ConfigFile_ParseAllInterfaces(long jarg1, ConfigFile jarg1_);
  public final static native int ConfigFile_GetSectionCount(long jarg1, ConfigFile jarg1_);
  public final static native String ConfigFile_GetSectionType(long jarg1, ConfigFile jarg1_, int jarg2);
  public final static native int ConfigFile_LookupSection(long jarg1, ConfigFile jarg1_, String jarg2);
  public final static native int ConfigFile_GetSectionParent(long jarg1, ConfigFile jarg1_, int jarg2);
  public final static native void ConfigFile_DumpTokens(long jarg1, ConfigFile jarg1_);
  public final static native void ConfigFile_DumpSections(long jarg1, ConfigFile jarg1_);
  public final static native void ConfigFile_DumpFields(long jarg1, ConfigFile jarg1_);
  public final static native void ConfigFile_filename_set(long jarg1, ConfigFile jarg1_, String jarg2);
  public final static native String ConfigFile_filename_get(long jarg1, ConfigFile jarg1_);
  public final static native int LOCALHOST_ADDR_get();
  public final static native long new_Device(long jarg1, player_devaddr_t jarg1_, long jarg2, Driver jarg2_);
  public final static native void delete_Device(long jarg1);
  public final static native int Device_Subscribe(long jarg1, Device jarg1_, long jarg2, QueuePointer jarg2_);
  public final static native int Device_Unsubscribe(long jarg1, Device jarg1_, long jarg2, QueuePointer jarg2_);
  public final static native void Device_PutMsg__SWIG_0(long jarg1, Device jarg1_, long jarg2, QueuePointer jarg2_, short jarg3, short jarg4, long jarg5, long jarg6, long jarg7);
  public final static native void Device_PutMsg__SWIG_1(long jarg1, Device jarg1_, long jarg2, QueuePointer jarg2_, long jarg3, player_msghdr_t jarg3_, long jarg4, boolean jarg5);
  public final static native void Device_PutMsg__SWIG_2(long jarg1, Device jarg1_, long jarg2, QueuePointer jarg2_, long jarg3, player_msghdr_t jarg3_, long jarg4);
  public final static native long Device_Request__SWIG_0(long jarg1, Device jarg1_, long jarg2, QueuePointer jarg2_, short jarg3, short jarg4, long jarg5, long jarg6, long jarg7, boolean jarg8);
  public final static native long Device_Request__SWIG_1(long jarg1, Device jarg1_, long jarg2, QueuePointer jarg2_, short jarg3, short jarg4, long jarg5, long jarg6, long jarg7);
  public final static native boolean Device_MatchDeviceAddress(long jarg1, player_devaddr_t jarg1_, long jarg2, player_devaddr_t jarg2_);
  public final static native void Device_next_set(long jarg1, Device jarg1_, long jarg2, Device jarg2_);
  public final static native long Device_next_get(long jarg1, Device jarg1_);
  public final static native void Device_addr_set(long jarg1, Device jarg1_, long jarg2, player_devaddr_t jarg2_);
  public final static native long Device_addr_get(long jarg1, Device jarg1_);
  public final static native void Device_drivername_set(long jarg1, Device jarg1_, String jarg2);
  public final static native String Device_drivername_get(long jarg1, Device jarg1_);
  public final static native void Device_driver_set(long jarg1, Device jarg1_, long jarg2, Driver jarg2_);
  public final static native long Device_driver_get(long jarg1, Device jarg1_);
  public final static native void Device_InQueue_set(long jarg1, Device jarg1_, long jarg2, QueuePointer jarg2_);
  public final static native long Device_InQueue_get(long jarg1, Device jarg1_);
  public final static native void Device_queues_set(long jarg1, Device jarg1_, long jarg2, QueuePointer jarg2_);
  public final static native long Device_queues_get(long jarg1, Device jarg1_);
  public final static native void Device_len_queues_set(long jarg1, Device jarg1_, long jarg2);
  public final static native long Device_len_queues_get(long jarg1, Device jarg1_);
  public final static native long new_DeviceTable();
  public final static native void delete_DeviceTable(long jarg1);
  public final static native long DeviceTable_AddDevice__SWIG_0(long jarg1, DeviceTable jarg1_, long jarg2, player_devaddr_t jarg2_, long jarg3, Driver jarg3_, boolean jarg4);
  public final static native long DeviceTable_AddDevice__SWIG_1(long jarg1, DeviceTable jarg1_, long jarg2, player_devaddr_t jarg2_, long jarg3, Driver jarg3_);
  public final static native long DeviceTable_GetDevice__SWIG_0(long jarg1, DeviceTable jarg1_, long jarg2, player_devaddr_t jarg2_, boolean jarg3);
  public final static native long DeviceTable_GetDevice__SWIG_1(long jarg1, DeviceTable jarg1_, long jarg2, player_devaddr_t jarg2_);
  public final static native long DeviceTable_GetDevice__SWIG_2(long jarg1, DeviceTable jarg1_, String jarg2, boolean jarg3);
  public final static native long DeviceTable_GetDevice__SWIG_3(long jarg1, DeviceTable jarg1_, String jarg2);
  public final static native long DeviceTable_GetFirstDevice(long jarg1, DeviceTable jarg1_);
  public final static native long DeviceTable_GetNextDevice(long jarg1, DeviceTable jarg1_, long jarg2, Device jarg2_);
  public final static native int DeviceTable_Size(long jarg1, DeviceTable jarg1_);
  public final static native void DeviceTable_UpdateDevices(long jarg1, DeviceTable jarg1_);
  public final static native int DeviceTable_StartAlwaysonDrivers(long jarg1, DeviceTable jarg1_);
  public final static native void DeviceTable_AddRemoteDriverFn(long jarg1, DeviceTable jarg1_, long jarg2, long jarg3);
  public final static native void Driver_StartThread(long jarg1, Driver jarg1_);
  public final static native void Driver_StartThreadSwigExplicitDriver(long jarg1, Driver jarg1_);
  public final static native void Driver_StopThread(long jarg1, Driver jarg1_);
  public final static native void Driver_StopThreadSwigExplicitDriver(long jarg1, Driver jarg1_);
  public final static native void Driver_driverthread_set(long jarg1, Driver jarg1_, long jarg2);
  public final static native long Driver_driverthread_get(long jarg1, Driver jarg1_);
  public final static native void Driver_Lock(long jarg1, Driver jarg1_);
  public final static native void Driver_Unlock(long jarg1, Driver jarg1_);
  public final static native void Driver_ret_queue_set(long jarg1, Driver jarg1_, long jarg2, QueuePointer jarg2_);
  public final static native long Driver_ret_queue_get(long jarg1, Driver jarg1_);
  public final static native void Driver_Publish__SWIG_0(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, long jarg3, QueuePointer jarg3_, short jarg4, short jarg5, long jarg6, long jarg7, long jarg8, boolean jarg9);
  public final static native void Driver_PublishSwigExplicitDriver__SWIG_0(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, long jarg3, QueuePointer jarg3_, short jarg4, short jarg5, long jarg6, long jarg7, long jarg8, boolean jarg9);
  public final static native void Driver_Publish__SWIG_1(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, long jarg3, QueuePointer jarg3_, short jarg4, short jarg5, long jarg6, long jarg7, long jarg8);
  public final static native void Driver_PublishSwigExplicitDriver__SWIG_1(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, long jarg3, QueuePointer jarg3_, short jarg4, short jarg5, long jarg6, long jarg7, long jarg8);
  public final static native void Driver_Publish__SWIG_2(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, long jarg3, QueuePointer jarg3_, short jarg4, short jarg5, long jarg6, long jarg7);
  public final static native void Driver_PublishSwigExplicitDriver__SWIG_2(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, long jarg3, QueuePointer jarg3_, short jarg4, short jarg5, long jarg6, long jarg7);
  public final static native void Driver_Publish__SWIG_3(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, long jarg3, QueuePointer jarg3_, short jarg4, short jarg5, long jarg6);
  public final static native void Driver_PublishSwigExplicitDriver__SWIG_3(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, long jarg3, QueuePointer jarg3_, short jarg4, short jarg5, long jarg6);
  public final static native void Driver_Publish__SWIG_4(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, long jarg3, QueuePointer jarg3_, short jarg4, short jarg5);
  public final static native void Driver_PublishSwigExplicitDriver__SWIG_4(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, long jarg3, QueuePointer jarg3_, short jarg4, short jarg5);
  public final static native void Driver_Publish__SWIG_5(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, short jarg3, short jarg4, long jarg5, long jarg6, long jarg7, boolean jarg8);
  public final static native void Driver_PublishSwigExplicitDriver__SWIG_5(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, short jarg3, short jarg4, long jarg5, long jarg6, long jarg7, boolean jarg8);
  public final static native void Driver_Publish__SWIG_6(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, short jarg3, short jarg4, long jarg5, long jarg6, long jarg7);
  public final static native void Driver_PublishSwigExplicitDriver__SWIG_6(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, short jarg3, short jarg4, long jarg5, long jarg6, long jarg7);
  public final static native void Driver_Publish__SWIG_7(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, short jarg3, short jarg4, long jarg5, long jarg6);
  public final static native void Driver_PublishSwigExplicitDriver__SWIG_7(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, short jarg3, short jarg4, long jarg5, long jarg6);
  public final static native void Driver_Publish__SWIG_8(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, short jarg3, short jarg4, long jarg5);
  public final static native void Driver_PublishSwigExplicitDriver__SWIG_8(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, short jarg3, short jarg4, long jarg5);
  public final static native void Driver_Publish__SWIG_9(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, short jarg3, short jarg4);
  public final static native void Driver_PublishSwigExplicitDriver__SWIG_9(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_, short jarg3, short jarg4);
  public final static native void Driver_Publish__SWIG_10(long jarg1, Driver jarg1_, long jarg2, QueuePointer jarg2_, long jarg3, player_msghdr_t jarg3_, long jarg4, boolean jarg5);
  public final static native void Driver_PublishSwigExplicitDriver__SWIG_10(long jarg1, Driver jarg1_, long jarg2, QueuePointer jarg2_, long jarg3, player_msghdr_t jarg3_, long jarg4, boolean jarg5);
  public final static native void Driver_Publish__SWIG_11(long jarg1, Driver jarg1_, long jarg2, QueuePointer jarg2_, long jarg3, player_msghdr_t jarg3_, long jarg4);
  public final static native void Driver_PublishSwigExplicitDriver__SWIG_11(long jarg1, Driver jarg1_, long jarg2, QueuePointer jarg2_, long jarg3, player_msghdr_t jarg3_, long jarg4);
  public final static native void Driver_Publish__SWIG_12(long jarg1, Driver jarg1_, long jarg2, player_msghdr_t jarg2_, long jarg3, boolean jarg4);
  public final static native void Driver_PublishSwigExplicitDriver__SWIG_12(long jarg1, Driver jarg1_, long jarg2, player_msghdr_t jarg2_, long jarg3, boolean jarg4);
  public final static native void Driver_Publish__SWIG_13(long jarg1, Driver jarg1_, long jarg2, player_msghdr_t jarg2_, long jarg3);
  public final static native void Driver_PublishSwigExplicitDriver__SWIG_13(long jarg1, Driver jarg1_, long jarg2, player_msghdr_t jarg2_, long jarg3);
  public final static native void Driver_device_addr_set(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_);
  public final static native long Driver_device_addr_get(long jarg1, Driver jarg1_);
  public final static native void Driver_subscriptions_set(long jarg1, Driver jarg1_, int jarg2);
  public final static native int Driver_subscriptions_get(long jarg1, Driver jarg1_);
  public final static native void Driver_entries_set(long jarg1, Driver jarg1_, int jarg2);
  public final static native int Driver_entries_get(long jarg1, Driver jarg1_);
  public final static native void Driver_alwayson_set(long jarg1, Driver jarg1_, boolean jarg2);
  public final static native boolean Driver_alwayson_get(long jarg1, Driver jarg1_);
  public final static native void Driver_InQueue_set(long jarg1, Driver jarg1_, long jarg2, QueuePointer jarg2_);
  public final static native long Driver_InQueue_get(long jarg1, Driver jarg1_);
  public final static native long new_Driver__SWIG_0(long jarg1, ConfigFile jarg1_, int jarg2, boolean jarg3, long jarg4, int jarg5);
  public final static native long new_Driver__SWIG_1(long jarg1, ConfigFile jarg1_, int jarg2, boolean jarg3, long jarg4);
  public final static native long new_Driver__SWIG_2(long jarg1, ConfigFile jarg1_, int jarg2, boolean jarg3);
  public final static native long new_Driver__SWIG_3(long jarg1, ConfigFile jarg1_, int jarg2);
  public final static native void delete_Driver(long jarg1);
  public final static native int Driver_GetError(long jarg1, Driver jarg1_);
  public final static native int Driver_Subscribe__SWIG_0(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_);
  public final static native int Driver_Subscribe__SWIG_1(long jarg1, Driver jarg1_, long jarg2, QueuePointer jarg2_, long jarg3, player_devaddr_t jarg3_);
  public final static native int Driver_Unsubscribe__SWIG_0(long jarg1, Driver jarg1_, long jarg2, player_devaddr_t jarg2_);
  public final static native int Driver_Unsubscribe__SWIG_1(long jarg1, Driver jarg1_, long jarg2, QueuePointer jarg2_, long jarg3, player_devaddr_t jarg3_);
  public final static native int Driver_Setup(long jarg1, Driver jarg1_);
  public final static native int Driver_Shutdown(long jarg1, Driver jarg1_);
  public final static native void Driver_Main(long jarg1, Driver jarg1_);
  public final static native void Driver_MainSwigExplicitDriver(long jarg1, Driver jarg1_);
  public final static native void Driver_MainQuit(long jarg1, Driver jarg1_);
  public final static native void Driver_MainQuitSwigExplicitDriver(long jarg1, Driver jarg1_);
  public final static native void Driver_ProcessMessages__SWIG_0(long jarg1, Driver jarg1_, int jarg2);
  public final static native void Driver_ProcessMessages__SWIG_1(long jarg1, Driver jarg1_);
  public final static native int Driver_ProcessMessage(long jarg1, Driver jarg1_, long jarg2, QueuePointer jarg2_, long jarg3, player_msghdr_t jarg3_, long jarg4);
  public final static native void Driver_Update(long jarg1, Driver jarg1_);
  public final static native void Driver_UpdateSwigExplicitDriver(long jarg1, Driver jarg1_);
  public final static native int Driver_ProcessInternalMessages(long jarg1, Driver jarg1_, long jarg2, QueuePointer jarg2_, long jarg3, player_msghdr_t jarg3_, long jarg4);
  public final static native int Driver_ProcessInternalMessagesSwigExplicitDriver(long jarg1, Driver jarg1_, long jarg2, QueuePointer jarg2_, long jarg3, player_msghdr_t jarg3_, long jarg4);
  public final static native boolean Driver_RegisterProperty__SWIG_0(long jarg1, Driver jarg1_, String jarg2, long jarg3, long jarg4, ConfigFile jarg4_, int jarg5);
  public final static native boolean Driver_RegisterPropertySwigExplicitDriver__SWIG_0(long jarg1, Driver jarg1_, String jarg2, long jarg3, long jarg4, ConfigFile jarg4_, int jarg5);
  public final static native boolean Driver_RegisterProperty__SWIG_1(long jarg1, Driver jarg1_, long jarg2, long jarg3, ConfigFile jarg3_, int jarg4);
  public final static native boolean Driver_RegisterPropertySwigExplicitDriver__SWIG_1(long jarg1, Driver jarg1_, long jarg2, long jarg3, ConfigFile jarg3_, int jarg4);
  public final static native void Driver_director_connect(Driver obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void Driver_change_ownership(Driver obj, long cptr, boolean take_or_release);
  public final static native void DriverEntry_initfunc_set(long jarg1, DriverEntry jarg1_, long jarg2);
  public final static native long DriverEntry_initfunc_get(long jarg1, DriverEntry jarg1_);
  public final static native void DriverEntry_name_set(long jarg1, DriverEntry jarg1_, String jarg2);
  public final static native String DriverEntry_name_get(long jarg1, DriverEntry jarg1_);
  public final static native void DriverEntry_next_set(long jarg1, DriverEntry jarg1_, long jarg2, DriverEntry jarg2_);
  public final static native long DriverEntry_next_get(long jarg1, DriverEntry jarg1_);
  public final static native long new_DriverEntry();
  public final static native void delete_DriverEntry(long jarg1);
  public final static native long new_DriverTable();
  public final static native void delete_DriverTable(long jarg1);
  public final static native int DriverTable_AddDriver(long jarg1, DriverTable jarg1_, String jarg2, long jarg3);
  public final static native long DriverTable_GetDriverEntry(long jarg1, DriverTable jarg1_, String jarg2);
  public final static native int DriverTable_Size(long jarg1, DriverTable jarg1_);
  public final static native String DriverTable_GetDriverName(long jarg1, DriverTable jarg1_, int jarg2);
  public final static native long DriverTable_SortDrivers(long jarg1, DriverTable jarg1_);
  public final static native void ErrorInit(int jarg1);
  public final static native void DefaultErrorPrint(int jarg1, int jarg2, String jarg3, int jarg4, String jarg5);
  public final static native void ErrorPrint_set(long jarg1);
  public final static native long ErrorPrint_get();
  public final static native void msgLevel_set(int jarg1);
  public final static native int msgLevel_get();
  public final static native void msgFile_set(long jarg1);
  public final static native long msgFile_get();
  public final static native int PLAYER_ERR_ERR_get();
  public final static native int PLAYER_ERR_WARN_get();
  public final static native int PLAYER_ERR_MSG_get();
  public final static native int PLAYER_ERR_DBG_get();
  public final static native long deviceTable_get();
  public final static native long GlobalTime_get();
  public final static native long driverTable_get();
  public final static native long fileWatcher_get();
  public final static native String playerversion_get();
  public final static native boolean player_quit_get();
  public final static native boolean player_quiet_startup_get();
  public final static native int player_argc_get();
  public final static native long player_argv_get();
  public final static native void player_globals_init();
  public final static native void player_globals_fini();
  public final static native long new_QueuePointer__SWIG_0();
  public final static native long new_QueuePointer__SWIG_1(boolean jarg1, long jarg2);
  public final static native void delete_QueuePointer(long jarg1);
  public final static native long new_QueuePointer__SWIG_2(long jarg1, QueuePointer jarg1_);
  public final static native long QueuePointer___deref__(long jarg1, QueuePointer jarg1_);
  public final static native long QueuePointer_get(long jarg1, QueuePointer jarg1_);
  public final static native long QueuePointer___ref__(long jarg1, QueuePointer jarg1_);
  public final static native boolean QueuePointer_Empty(long jarg1, QueuePointer jarg1_);
  public final static native boolean QueuePointer_Push(long jarg1, QueuePointer jarg1_, long jarg2, Message jarg2_);
  public final static native void QueuePointer_PushFront(long jarg1, QueuePointer jarg1_, long jarg2, Message jarg2_, boolean jarg3);
  public final static native void QueuePointer_PushBack(long jarg1, QueuePointer jarg1_, long jarg2, Message jarg2_, boolean jarg3);
  public final static native long QueuePointer_Pop(long jarg1, QueuePointer jarg1_);
  public final static native void QueuePointer_SetReplace(long jarg1, QueuePointer jarg1_, boolean jarg2);
  public final static native void QueuePointer_AddReplaceRule__SWIG_0(long jarg1, QueuePointer jarg1_, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8);
  public final static native void QueuePointer_AddReplaceRule__SWIG_1(long jarg1, QueuePointer jarg1_, long jarg2, player_devaddr_t jarg2_, int jarg3, int jarg4, int jarg5);
  public final static native int QueuePointer_CheckReplace(long jarg1, QueuePointer jarg1_, long jarg2, player_msghdr_t jarg2_);
  public final static native boolean QueuePointer_Wait__SWIG_0(long jarg1, QueuePointer jarg1_, double jarg2);
  public final static native boolean QueuePointer_Wait__SWIG_1(long jarg1, QueuePointer jarg1_);
  public final static native void QueuePointer_DataAvailable(long jarg1, QueuePointer jarg1_);
  public final static native boolean QueuePointer_Filter(long jarg1, QueuePointer jarg1_, long jarg2, Message jarg2_);
  public final static native void QueuePointer_ClearFilter(long jarg1, QueuePointer jarg1_);
  public final static native void QueuePointer_SetFilter(long jarg1, QueuePointer jarg1_, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7);
  public final static native void QueuePointer_SetPull(long jarg1, QueuePointer jarg1_, boolean jarg2);
  public final static native long QueuePointer_GetLength(long jarg1, QueuePointer jarg1_);
  public final static native void QueuePointer_SetDataRequested(long jarg1, QueuePointer jarg1_, boolean jarg2, boolean jarg3);
  public final static native long new_Message__SWIG_0(long jarg1, player_msghdr_t jarg1_, long jarg2, boolean jarg3);
  public final static native long new_Message__SWIG_1(long jarg1, player_msghdr_t jarg1_, long jarg2);
  public final static native long new_Message__SWIG_2(long jarg1, player_msghdr_t jarg1_, long jarg2, long jarg3, QueuePointer jarg3_, boolean jarg4);
  public final static native long new_Message__SWIG_3(long jarg1, player_msghdr_t jarg1_, long jarg2, long jarg3, QueuePointer jarg3_);
  public final static native long new_Message__SWIG_4(long jarg1, Message jarg1_);
  public final static native void delete_Message(long jarg1);
  public final static native boolean Message_MatchMessage__SWIG_0(long jarg1, player_msghdr_t jarg1_, int jarg2, int jarg3, long jarg4, player_devaddr_t jarg4_);
  public final static native boolean Message_MatchMessage__SWIG_1(long jarg1, player_msghdr_t jarg1_, int jarg2, int jarg3);
  public final static native long Message_GetHeader(long jarg1, Message jarg1_);
  public final static native long Message_GetPayload(long jarg1, Message jarg1_);
  public final static native long Message_GetDataSize(long jarg1, Message jarg1_);
  public final static native boolean Message_Compare(long jarg1, Message jarg1_, long jarg2, Message jarg2_);
  public final static native void Message_DecRef(long jarg1, Message jarg1_);
  public final static native void Message_Queue_set(long jarg1, Message jarg1_, long jarg2, QueuePointer jarg2_);
  public final static native long Message_Queue_get(long jarg1, Message jarg1_);
  public final static native void Message_RefCount_set(long jarg1, Message jarg1_, long jarg2);
  public final static native long Message_RefCount_get(long jarg1, Message jarg1_);
  public final static native long new_MessageQueueElement();
  public final static native void delete_MessageQueueElement(long jarg1);
  public final static native void MessageQueueElement_msg_set(long jarg1, MessageQueueElement jarg1_, long jarg2, Message jarg2_);
  public final static native long MessageQueueElement_msg_get(long jarg1, MessageQueueElement jarg1_);
  public final static native long new_MessageReplaceRule(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7);
  public final static native boolean MessageReplaceRule_Match(long jarg1, MessageReplaceRule jarg1_, long jarg2, player_msghdr_t jarg2_);
  public final static native boolean MessageReplaceRule_Equivalent(long jarg1, MessageReplaceRule jarg1_, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7);
  public final static native void MessageReplaceRule_replace_set(long jarg1, MessageReplaceRule jarg1_, int jarg2);
  public final static native int MessageReplaceRule_replace_get(long jarg1, MessageReplaceRule jarg1_);
  public final static native void MessageReplaceRule_next_set(long jarg1, MessageReplaceRule jarg1_, long jarg2, MessageReplaceRule jarg2_);
  public final static native long MessageReplaceRule_next_get(long jarg1, MessageReplaceRule jarg1_);
  public final static native void delete_MessageReplaceRule(long jarg1);
  public final static native long new_MessageQueue(boolean jarg1, long jarg2);
  public final static native void delete_MessageQueue(long jarg1);
  public final static native boolean MessageQueue_Empty(long jarg1, MessageQueue jarg1_);
  public final static native boolean MessageQueue_Push(long jarg1, MessageQueue jarg1_, long jarg2, Message jarg2_);
  public final static native void MessageQueue_PushFront(long jarg1, MessageQueue jarg1_, long jarg2, Message jarg2_, boolean jarg3);
  public final static native void MessageQueue_PushBack(long jarg1, MessageQueue jarg1_, long jarg2, Message jarg2_, boolean jarg3);
  public final static native long MessageQueue_Pop(long jarg1, MessageQueue jarg1_);
  public final static native void MessageQueue_SetReplace(long jarg1, MessageQueue jarg1_, boolean jarg2);
  public final static native void MessageQueue_AddReplaceRule__SWIG_0(long jarg1, MessageQueue jarg1_, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8);
  public final static native void MessageQueue_AddReplaceRule__SWIG_1(long jarg1, MessageQueue jarg1_, long jarg2, player_devaddr_t jarg2_, int jarg3, int jarg4, int jarg5);
  public final static native int MessageQueue_CheckReplace(long jarg1, MessageQueue jarg1_, long jarg2, player_msghdr_t jarg2_);
  public final static native boolean MessageQueue_Wait__SWIG_0(long jarg1, MessageQueue jarg1_, double jarg2);
  public final static native boolean MessageQueue_Wait__SWIG_1(long jarg1, MessageQueue jarg1_);
  public final static native void MessageQueue_DataAvailable(long jarg1, MessageQueue jarg1_);
  public final static native boolean MessageQueue_Filter(long jarg1, MessageQueue jarg1_, long jarg2, Message jarg2_);
  public final static native void MessageQueue_ClearFilter(long jarg1, MessageQueue jarg1_);
  public final static native void MessageQueue_SetFilter(long jarg1, MessageQueue jarg1_, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7);
  public final static native void MessageQueue_SetPull(long jarg1, MessageQueue jarg1_, boolean jarg2);
  public final static native long MessageQueue_GetLength(long jarg1, MessageQueue jarg1_);
  public final static native void MessageQueue_SetDataRequested(long jarg1, MessageQueue jarg1_, boolean jarg2, boolean jarg3);
  public final static native int PLAYER_MAX_MESSAGE_SIZE_get();
  public final static native int PLAYER_MAX_DRIVER_STRING_LEN_get();
  public final static native int PLAYER_MAX_DEVICES_get();
  public final static native int PLAYER_MSGQUEUE_DEFAULT_MAXLEN_get();
  public final static native String PLAYER_IDENT_STRING_get();
  public final static native int PLAYER_IDENT_STRLEN_get();
  public final static native int PLAYER_KEYLEN_get();
  public final static native int PLAYER_MSGTYPE_DATA_get();
  public final static native int PLAYER_MSGTYPE_CMD_get();
  public final static native int PLAYER_MSGTYPE_REQ_get();
  public final static native int PLAYER_MSGTYPE_RESP_ACK_get();
  public final static native int PLAYER_MSGTYPE_SYNCH_get();
  public final static native int PLAYER_MSGTYPE_RESP_NACK_get();
  public final static native void player_devaddr_t_host_set(long jarg1, player_devaddr_t jarg1_, long jarg2);
  public final static native long player_devaddr_t_host_get(long jarg1, player_devaddr_t jarg1_);
  public final static native void player_devaddr_t_robot_set(long jarg1, player_devaddr_t jarg1_, long jarg2);
  public final static native long player_devaddr_t_robot_get(long jarg1, player_devaddr_t jarg1_);
  public final static native void player_devaddr_t_interf_set(long jarg1, player_devaddr_t jarg1_, int jarg2);
  public final static native int player_devaddr_t_interf_get(long jarg1, player_devaddr_t jarg1_);
  public final static native void player_devaddr_t_index_set(long jarg1, player_devaddr_t jarg1_, int jarg2);
  public final static native int player_devaddr_t_index_get(long jarg1, player_devaddr_t jarg1_);
  public final static native long new_player_devaddr_t();
  public final static native void delete_player_devaddr_t(long jarg1);
  public final static native void player_msghdr_t_addr_set(long jarg1, player_msghdr_t jarg1_, long jarg2, player_devaddr_t jarg2_);
  public final static native long player_msghdr_t_addr_get(long jarg1, player_msghdr_t jarg1_);
  public final static native void player_msghdr_t_type_set(long jarg1, player_msghdr_t jarg1_, short jarg2);
  public final static native short player_msghdr_t_type_get(long jarg1, player_msghdr_t jarg1_);
  public final static native void player_msghdr_t_subtype_set(long jarg1, player_msghdr_t jarg1_, short jarg2);
  public final static native short player_msghdr_t_subtype_get(long jarg1, player_msghdr_t jarg1_);
  public final static native void player_msghdr_t_timestamp_set(long jarg1, player_msghdr_t jarg1_, double jarg2);
  public final static native double player_msghdr_t_timestamp_get(long jarg1, player_msghdr_t jarg1_);
  public final static native void player_msghdr_t_seq_set(long jarg1, player_msghdr_t jarg1_, long jarg2);
  public final static native long player_msghdr_t_seq_get(long jarg1, player_msghdr_t jarg1_);
  public final static native void player_msghdr_t_size_set(long jarg1, player_msghdr_t jarg1_, long jarg2);
  public final static native long player_msghdr_t_size_get(long jarg1, player_msghdr_t jarg1_);
  public final static native long new_player_msghdr_t();
  public final static native void delete_player_msghdr_t(long jarg1);
  public final static native long new_player_null_t();
  public final static native void delete_player_null_t(long jarg1);
  public final static native void player_point_2d_t_px_set(long jarg1, player_point_2d_t jarg1_, double jarg2);
  public final static native double player_point_2d_t_px_get(long jarg1, player_point_2d_t jarg1_);
  public final static native void player_point_2d_t_py_set(long jarg1, player_point_2d_t jarg1_, double jarg2);
  public final static native double player_point_2d_t_py_get(long jarg1, player_point_2d_t jarg1_);
  public final static native long new_player_point_2d_t();
  public final static native void delete_player_point_2d_t(long jarg1);
  public final static native void player_point_3d_t_px_set(long jarg1, player_point_3d_t jarg1_, double jarg2);
  public final static native double player_point_3d_t_px_get(long jarg1, player_point_3d_t jarg1_);
  public final static native void player_point_3d_t_py_set(long jarg1, player_point_3d_t jarg1_, double jarg2);
  public final static native double player_point_3d_t_py_get(long jarg1, player_point_3d_t jarg1_);
  public final static native void player_point_3d_t_pz_set(long jarg1, player_point_3d_t jarg1_, double jarg2);
  public final static native double player_point_3d_t_pz_get(long jarg1, player_point_3d_t jarg1_);
  public final static native long new_player_point_3d_t();
  public final static native void delete_player_point_3d_t(long jarg1);
  public final static native void player_orientation_3d_t_proll_set(long jarg1, player_orientation_3d_t jarg1_, double jarg2);
  public final static native double player_orientation_3d_t_proll_get(long jarg1, player_orientation_3d_t jarg1_);
  public final static native void player_orientation_3d_t_ppitch_set(long jarg1, player_orientation_3d_t jarg1_, double jarg2);
  public final static native double player_orientation_3d_t_ppitch_get(long jarg1, player_orientation_3d_t jarg1_);
  public final static native void player_orientation_3d_t_pyaw_set(long jarg1, player_orientation_3d_t jarg1_, double jarg2);
  public final static native double player_orientation_3d_t_pyaw_get(long jarg1, player_orientation_3d_t jarg1_);
  public final static native long new_player_orientation_3d_t();
  public final static native void delete_player_orientation_3d_t(long jarg1);
  public final static native void player_pose2d_t_px_set(long jarg1, player_pose2d_t jarg1_, double jarg2);
  public final static native double player_pose2d_t_px_get(long jarg1, player_pose2d_t jarg1_);
  public final static native void player_pose2d_t_py_set(long jarg1, player_pose2d_t jarg1_, double jarg2);
  public final static native double player_pose2d_t_py_get(long jarg1, player_pose2d_t jarg1_);
  public final static native void player_pose2d_t_pa_set(long jarg1, player_pose2d_t jarg1_, double jarg2);
  public final static native double player_pose2d_t_pa_get(long jarg1, player_pose2d_t jarg1_);
  public final static native long new_player_pose2d_t();
  public final static native void delete_player_pose2d_t(long jarg1);
  public final static native void player_pose3d_t_px_set(long jarg1, player_pose3d_t jarg1_, double jarg2);
  public final static native double player_pose3d_t_px_get(long jarg1, player_pose3d_t jarg1_);
  public final static native void player_pose3d_t_py_set(long jarg1, player_pose3d_t jarg1_, double jarg2);
  public final static native double player_pose3d_t_py_get(long jarg1, player_pose3d_t jarg1_);
  public final static native void player_pose3d_t_pz_set(long jarg1, player_pose3d_t jarg1_, double jarg2);
  public final static native double player_pose3d_t_pz_get(long jarg1, player_pose3d_t jarg1_);
  public final static native void player_pose3d_t_proll_set(long jarg1, player_pose3d_t jarg1_, double jarg2);
  public final static native double player_pose3d_t_proll_get(long jarg1, player_pose3d_t jarg1_);
  public final static native void player_pose3d_t_ppitch_set(long jarg1, player_pose3d_t jarg1_, double jarg2);
  public final static native double player_pose3d_t_ppitch_get(long jarg1, player_pose3d_t jarg1_);
  public final static native void player_pose3d_t_pyaw_set(long jarg1, player_pose3d_t jarg1_, double jarg2);
  public final static native double player_pose3d_t_pyaw_get(long jarg1, player_pose3d_t jarg1_);
  public final static native long new_player_pose3d_t();
  public final static native void delete_player_pose3d_t(long jarg1);
  public final static native void player_bbox2d_t_sw_set(long jarg1, player_bbox2d_t jarg1_, double jarg2);
  public final static native double player_bbox2d_t_sw_get(long jarg1, player_bbox2d_t jarg1_);
  public final static native void player_bbox2d_t_sl_set(long jarg1, player_bbox2d_t jarg1_, double jarg2);
  public final static native double player_bbox2d_t_sl_get(long jarg1, player_bbox2d_t jarg1_);
  public final static native long new_player_bbox2d_t();
  public final static native void delete_player_bbox2d_t(long jarg1);
  public final static native void player_bbox3d_t_sw_set(long jarg1, player_bbox3d_t jarg1_, double jarg2);
  public final static native double player_bbox3d_t_sw_get(long jarg1, player_bbox3d_t jarg1_);
  public final static native void player_bbox3d_t_sl_set(long jarg1, player_bbox3d_t jarg1_, double jarg2);
  public final static native double player_bbox3d_t_sl_get(long jarg1, player_bbox3d_t jarg1_);
  public final static native void player_bbox3d_t_sh_set(long jarg1, player_bbox3d_t jarg1_, double jarg2);
  public final static native double player_bbox3d_t_sh_get(long jarg1, player_bbox3d_t jarg1_);
  public final static native long new_player_bbox3d_t();
  public final static native void delete_player_bbox3d_t(long jarg1);
  public final static native void player_blackboard_entry_t_key_count_set(long jarg1, player_blackboard_entry_t jarg1_, long jarg2);
  public final static native long player_blackboard_entry_t_key_count_get(long jarg1, player_blackboard_entry_t jarg1_);
  public final static native void player_blackboard_entry_t_key_set(long jarg1, player_blackboard_entry_t jarg1_, String jarg2);
  public final static native String player_blackboard_entry_t_key_get(long jarg1, player_blackboard_entry_t jarg1_);
  public final static native void player_blackboard_entry_t_group_count_set(long jarg1, player_blackboard_entry_t jarg1_, long jarg2);
  public final static native long player_blackboard_entry_t_group_count_get(long jarg1, player_blackboard_entry_t jarg1_);
  public final static native void player_blackboard_entry_t_group_set(long jarg1, player_blackboard_entry_t jarg1_, String jarg2);
  public final static native String player_blackboard_entry_t_group_get(long jarg1, player_blackboard_entry_t jarg1_);
  public final static native void player_blackboard_entry_t_type_set(long jarg1, player_blackboard_entry_t jarg1_, int jarg2);
  public final static native int player_blackboard_entry_t_type_get(long jarg1, player_blackboard_entry_t jarg1_);
  public final static native void player_blackboard_entry_t_subtype_set(long jarg1, player_blackboard_entry_t jarg1_, int jarg2);
  public final static native int player_blackboard_entry_t_subtype_get(long jarg1, player_blackboard_entry_t jarg1_);
  public final static native void player_blackboard_entry_t_data_count_set(long jarg1, player_blackboard_entry_t jarg1_, long jarg2);
  public final static native long player_blackboard_entry_t_data_count_get(long jarg1, player_blackboard_entry_t jarg1_);
  public final static native void player_blackboard_entry_t_data_set(long jarg1, player_blackboard_entry_t jarg1_, long jarg2);
  public final static native long player_blackboard_entry_t_data_get(long jarg1, player_blackboard_entry_t jarg1_);
  public final static native void player_blackboard_entry_t_timestamp_sec_set(long jarg1, player_blackboard_entry_t jarg1_, long jarg2);
  public final static native long player_blackboard_entry_t_timestamp_sec_get(long jarg1, player_blackboard_entry_t jarg1_);
  public final static native void player_blackboard_entry_t_timestamp_usec_set(long jarg1, player_blackboard_entry_t jarg1_, long jarg2);
  public final static native long player_blackboard_entry_t_timestamp_usec_get(long jarg1, player_blackboard_entry_t jarg1_);
  public final static native long new_player_blackboard_entry_t();
  public final static native void delete_player_blackboard_entry_t(long jarg1);
  public final static native void player_segment_t_x0_set(long jarg1, player_segment_t jarg1_, double jarg2);
  public final static native double player_segment_t_x0_get(long jarg1, player_segment_t jarg1_);
  public final static native void player_segment_t_y0_set(long jarg1, player_segment_t jarg1_, double jarg2);
  public final static native double player_segment_t_y0_get(long jarg1, player_segment_t jarg1_);
  public final static native void player_segment_t_x1_set(long jarg1, player_segment_t jarg1_, double jarg2);
  public final static native double player_segment_t_x1_get(long jarg1, player_segment_t jarg1_);
  public final static native void player_segment_t_y1_set(long jarg1, player_segment_t jarg1_, double jarg2);
  public final static native double player_segment_t_y1_get(long jarg1, player_segment_t jarg1_);
  public final static native long new_player_segment_t();
  public final static native void delete_player_segment_t(long jarg1);
  public final static native void player_extent2d_t_x0_set(long jarg1, player_extent2d_t jarg1_, double jarg2);
  public final static native double player_extent2d_t_x0_get(long jarg1, player_extent2d_t jarg1_);
  public final static native void player_extent2d_t_y0_set(long jarg1, player_extent2d_t jarg1_, double jarg2);
  public final static native double player_extent2d_t_y0_get(long jarg1, player_extent2d_t jarg1_);
  public final static native void player_extent2d_t_x1_set(long jarg1, player_extent2d_t jarg1_, double jarg2);
  public final static native double player_extent2d_t_x1_get(long jarg1, player_extent2d_t jarg1_);
  public final static native void player_extent2d_t_y1_set(long jarg1, player_extent2d_t jarg1_, double jarg2);
  public final static native double player_extent2d_t_y1_get(long jarg1, player_extent2d_t jarg1_);
  public final static native long new_player_extent2d_t();
  public final static native void delete_player_extent2d_t(long jarg1);
  public final static native void player_color_t_alpha_set(long jarg1, player_color_t jarg1_, short jarg2);
  public final static native short player_color_t_alpha_get(long jarg1, player_color_t jarg1_);
  public final static native void player_color_t_red_set(long jarg1, player_color_t jarg1_, short jarg2);
  public final static native short player_color_t_red_get(long jarg1, player_color_t jarg1_);
  public final static native void player_color_t_green_set(long jarg1, player_color_t jarg1_, short jarg2);
  public final static native short player_color_t_green_get(long jarg1, player_color_t jarg1_);
  public final static native void player_color_t_blue_set(long jarg1, player_color_t jarg1_, short jarg2);
  public final static native short player_color_t_blue_get(long jarg1, player_color_t jarg1_);
  public final static native long new_player_color_t();
  public final static native void delete_player_color_t(long jarg1);
  public final static native void player_bool_t_state_set(long jarg1, player_bool_t jarg1_, short jarg2);
  public final static native short player_bool_t_state_get(long jarg1, player_bool_t jarg1_);
  public final static native long new_player_bool_t();
  public final static native void delete_player_bool_t(long jarg1);
  public final static native void player_uint32_t_value_set(long jarg1, player_uint32_t jarg1_, long jarg2);
  public final static native long player_uint32_t_value_get(long jarg1, player_uint32_t jarg1_);
  public final static native long new_player_uint32_t();
  public final static native void delete_player_uint32_t(long jarg1);
  public final static native int PLAYER_CAPABILTIES_REQ_get();
  public final static native void player_capabilities_req_t_type_set(long jarg1, player_capabilities_req_t jarg1_, long jarg2);
  public final static native long player_capabilities_req_t_type_get(long jarg1, player_capabilities_req_t jarg1_);
  public final static native void player_capabilities_req_t_subtype_set(long jarg1, player_capabilities_req_t jarg1_, long jarg2);
  public final static native long player_capabilities_req_t_subtype_get(long jarg1, player_capabilities_req_t jarg1_);
  public final static native long new_player_capabilities_req_t();
  public final static native void delete_player_capabilities_req_t(long jarg1);
  public final static native int PLAYER_GET_INTPROP_REQ_get();
  public final static native int PLAYER_SET_INTPROP_REQ_get();
  public final static native int PLAYER_GET_DBLPROP_REQ_get();
  public final static native int PLAYER_SET_DBLPROP_REQ_get();
  public final static native int PLAYER_GET_STRPROP_REQ_get();
  public final static native int PLAYER_SET_STRPROP_REQ_get();
  public final static native void player_intprop_req_t_key_count_set(long jarg1, player_intprop_req_t jarg1_, long jarg2);
  public final static native long player_intprop_req_t_key_count_get(long jarg1, player_intprop_req_t jarg1_);
  public final static native void player_intprop_req_t_key_set(long jarg1, player_intprop_req_t jarg1_, String jarg2);
  public final static native String player_intprop_req_t_key_get(long jarg1, player_intprop_req_t jarg1_);
  public final static native void player_intprop_req_t_value_set(long jarg1, player_intprop_req_t jarg1_, int jarg2);
  public final static native int player_intprop_req_t_value_get(long jarg1, player_intprop_req_t jarg1_);
  public final static native long new_player_intprop_req_t();
  public final static native void delete_player_intprop_req_t(long jarg1);
  public final static native void player_dblprop_req_t_key_count_set(long jarg1, player_dblprop_req_t jarg1_, long jarg2);
  public final static native long player_dblprop_req_t_key_count_get(long jarg1, player_dblprop_req_t jarg1_);
  public final static native void player_dblprop_req_t_key_set(long jarg1, player_dblprop_req_t jarg1_, String jarg2);
  public final static native String player_dblprop_req_t_key_get(long jarg1, player_dblprop_req_t jarg1_);
  public final static native void player_dblprop_req_t_value_set(long jarg1, player_dblprop_req_t jarg1_, double jarg2);
  public final static native double player_dblprop_req_t_value_get(long jarg1, player_dblprop_req_t jarg1_);
  public final static native long new_player_dblprop_req_t();
  public final static native void delete_player_dblprop_req_t(long jarg1);
  public final static native void player_strprop_req_t_key_count_set(long jarg1, player_strprop_req_t jarg1_, long jarg2);
  public final static native long player_strprop_req_t_key_count_get(long jarg1, player_strprop_req_t jarg1_);
  public final static native void player_strprop_req_t_key_set(long jarg1, player_strprop_req_t jarg1_, String jarg2);
  public final static native String player_strprop_req_t_key_get(long jarg1, player_strprop_req_t jarg1_);
  public final static native void player_strprop_req_t_value_count_set(long jarg1, player_strprop_req_t jarg1_, long jarg2);
  public final static native long player_strprop_req_t_value_count_get(long jarg1, player_strprop_req_t jarg1_);
  public final static native void player_strprop_req_t_value_set(long jarg1, player_strprop_req_t jarg1_, String jarg2);
  public final static native String player_strprop_req_t_value_get(long jarg1, player_strprop_req_t jarg1_);
  public final static native long new_player_strprop_req_t();
  public final static native void delete_player_strprop_req_t(long jarg1);
  public final static native double M_PI_get();
  public final static native int PlayerTime_GetTime(long jarg1, PlayerTime jarg1_, long jarg2);
  public final static native int PlayerTime_GetTimeDouble(long jarg1, PlayerTime jarg1_, long jarg2);
  public final static native void delete_PlayerTime(long jarg1);
  public final static native void packedaddr_to_dottedip(String jarg1, long jarg2, long jarg3);
  public final static native void player_register_drivers();
  public final static native long player_devaddr_t_sizeof();
  public final static native long buf_to_player_devaddr_t(long jarg1);
  public final static native long player_devaddr_t_to_buf(long jarg1, player_devaddr_t jarg1_);
  public final static native long player_msghdr_t_sizeof();
  public final static native long buf_to_player_msghdr_t(long jarg1);
  public final static native long player_msghdr_t_to_buf(long jarg1, player_msghdr_t jarg1_);
  public final static native long player_null_t_sizeof();
  public final static native long buf_to_player_null_t(long jarg1);
  public final static native long player_null_t_to_buf(long jarg1, player_null_t jarg1_);
  public final static native long player_point_2d_t_sizeof();
  public final static native long buf_to_player_point_2d_t(long jarg1);
  public final static native long player_point_2d_t_to_buf(long jarg1, player_point_2d_t jarg1_);
  public final static native long player_point_3d_t_sizeof();
  public final static native long buf_to_player_point_3d_t(long jarg1);
  public final static native long player_point_3d_t_to_buf(long jarg1, player_point_3d_t jarg1_);
  public final static native long player_orientation_3d_t_sizeof();
  public final static native long buf_to_player_orientation_3d_t(long jarg1);
  public final static native long player_orientation_3d_t_to_buf(long jarg1, player_orientation_3d_t jarg1_);
  public final static native long player_pose2d_t_sizeof();
  public final static native long buf_to_player_pose2d_t(long jarg1);
  public final static native long player_pose2d_t_to_buf(long jarg1, player_pose2d_t jarg1_);
  public final static native long player_pose3d_t_sizeof();
  public final static native long buf_to_player_pose3d_t(long jarg1);
  public final static native long player_pose3d_t_to_buf(long jarg1, player_pose3d_t jarg1_);
  public final static native long player_bbox2d_t_sizeof();
  public final static native long buf_to_player_bbox2d_t(long jarg1);
  public final static native long player_bbox2d_t_to_buf(long jarg1, player_bbox2d_t jarg1_);
  public final static native long player_bbox3d_t_sizeof();
  public final static native long buf_to_player_bbox3d_t(long jarg1);
  public final static native long player_bbox3d_t_to_buf(long jarg1, player_bbox3d_t jarg1_);
  public final static native long player_blackboard_entry_t_sizeof();
  public final static native long buf_to_player_blackboard_entry_t(long jarg1);
  public final static native long player_blackboard_entry_t_to_buf(long jarg1, player_blackboard_entry_t jarg1_);
  public final static native long player_segment_t_sizeof();
  public final static native long buf_to_player_segment_t(long jarg1);
  public final static native long player_segment_t_to_buf(long jarg1, player_segment_t jarg1_);
  public final static native long player_extent2d_t_sizeof();
  public final static native long buf_to_player_extent2d_t(long jarg1);
  public final static native long player_extent2d_t_to_buf(long jarg1, player_extent2d_t jarg1_);
  public final static native long player_color_t_sizeof();
  public final static native long buf_to_player_color_t(long jarg1);
  public final static native long player_color_t_to_buf(long jarg1, player_color_t jarg1_);
  public final static native long player_bool_t_sizeof();
  public final static native long buf_to_player_bool_t(long jarg1);
  public final static native long player_bool_t_to_buf(long jarg1, player_bool_t jarg1_);
  public final static native long player_uint32_t_sizeof();
  public final static native long buf_to_player_uint32_t(long jarg1);
  public final static native long player_uint32_t_to_buf(long jarg1, player_uint32_t jarg1_);
  public final static native long player_capabilities_req_t_sizeof();
  public final static native long buf_to_player_capabilities_req_t(long jarg1);
  public final static native long player_capabilities_req_t_to_buf(long jarg1, player_capabilities_req_t jarg1_);
  public final static native long player_intprop_req_t_sizeof();
  public final static native long buf_to_player_intprop_req_t(long jarg1);
  public final static native long player_intprop_req_t_to_buf(long jarg1, player_intprop_req_t jarg1_);
  public final static native long player_dblprop_req_t_sizeof();
  public final static native long buf_to_player_dblprop_req_t(long jarg1);
  public final static native long player_dblprop_req_t_to_buf(long jarg1, player_dblprop_req_t jarg1_);
  public final static native long player_strprop_req_t_sizeof();
  public final static native long buf_to_player_strprop_req_t(long jarg1);
  public final static native long player_strprop_req_t_to_buf(long jarg1, player_strprop_req_t jarg1_);

  public static void SwigDirector_Driver_StartThread(Driver self) {
    self.StartThread();
  }
  public static void SwigDirector_Driver_StopThread(Driver self) {
    self.StopThread();
  }
  public static void SwigDirector_Driver_Publish__SWIG_0(Driver self, long addr, long queue, short type, short subtype, long src, long deprecated, long timestamp, boolean copy) {
    self.Publish(new player_devaddr_t(addr, false), new QueuePointer(queue, false), type, subtype, new SWIGTYPE_p_void(src, false), deprecated, new SWIGTYPE_p_double(timestamp, false), copy);
  }
  public static void SwigDirector_Driver_Publish__SWIG_1(Driver self, long addr, long queue, short type, short subtype, long src, long deprecated, long timestamp) {
    self.Publish(new player_devaddr_t(addr, false), new QueuePointer(queue, false), type, subtype, new SWIGTYPE_p_void(src, false), deprecated, new SWIGTYPE_p_double(timestamp, false));
  }
  public static void SwigDirector_Driver_Publish__SWIG_2(Driver self, long addr, long queue, short type, short subtype, long src, long deprecated) {
    self.Publish(new player_devaddr_t(addr, false), new QueuePointer(queue, false), type, subtype, new SWIGTYPE_p_void(src, false), deprecated);
  }
  public static void SwigDirector_Driver_Publish__SWIG_3(Driver self, long addr, long queue, short type, short subtype, long src) {
    self.Publish(new player_devaddr_t(addr, false), new QueuePointer(queue, false), type, subtype, new SWIGTYPE_p_void(src, false));
  }
  public static void SwigDirector_Driver_Publish__SWIG_4(Driver self, long addr, long queue, short type, short subtype) {
    self.Publish(new player_devaddr_t(addr, false), new QueuePointer(queue, false), type, subtype);
  }
  public static void SwigDirector_Driver_Publish__SWIG_5(Driver self, long addr, short type, short subtype, long src, long deprecated, long timestamp, boolean copy) {
    self.Publish(new player_devaddr_t(addr, false), type, subtype, new SWIGTYPE_p_void(src, false), deprecated, new SWIGTYPE_p_double(timestamp, false), copy);
  }
  public static void SwigDirector_Driver_Publish__SWIG_6(Driver self, long addr, short type, short subtype, long src, long deprecated, long timestamp) {
    self.Publish(new player_devaddr_t(addr, false), type, subtype, new SWIGTYPE_p_void(src, false), deprecated, new SWIGTYPE_p_double(timestamp, false));
  }
  public static void SwigDirector_Driver_Publish__SWIG_7(Driver self, long addr, short type, short subtype, long src, long deprecated) {
    self.Publish(new player_devaddr_t(addr, false), type, subtype, new SWIGTYPE_p_void(src, false), deprecated);
  }
  public static void SwigDirector_Driver_Publish__SWIG_8(Driver self, long addr, short type, short subtype, long src) {
    self.Publish(new player_devaddr_t(addr, false), type, subtype, new SWIGTYPE_p_void(src, false));
  }
  public static void SwigDirector_Driver_Publish__SWIG_9(Driver self, long addr, short type, short subtype) {
    self.Publish(new player_devaddr_t(addr, false), type, subtype);
  }
  public static void SwigDirector_Driver_Publish__SWIG_10(Driver self, long queue, long hdr, long src, boolean copy) {
    self.Publish(new QueuePointer(queue, false), new player_msghdr_t(hdr, false), new SWIGTYPE_p_void(src, false), copy);
  }
  public static void SwigDirector_Driver_Publish__SWIG_11(Driver self, long queue, long hdr, long src) {
    self.Publish(new QueuePointer(queue, false), new player_msghdr_t(hdr, false), new SWIGTYPE_p_void(src, false));
  }
  public static void SwigDirector_Driver_Publish__SWIG_12(Driver self, long hdr, long src, boolean copy) {
    self.Publish(new player_msghdr_t(hdr, false), new SWIGTYPE_p_void(src, false), copy);
  }
  public static void SwigDirector_Driver_Publish__SWIG_13(Driver self, long hdr, long src) {
    self.Publish(new player_msghdr_t(hdr, false), new SWIGTYPE_p_void(src, false));
  }
  public static int SwigDirector_Driver_Setup(Driver self) {
    return self.Setup();
  }
  public static int SwigDirector_Driver_Shutdown(Driver self) {
    return self.Shutdown();
  }
  public static void SwigDirector_Driver_Main(Driver self) {
    self.Main();
  }
  public static void SwigDirector_Driver_MainQuit(Driver self) {
    self.MainQuit();
  }
  public static void SwigDirector_Driver_Update(Driver self) {
    self.Update();
  }
  public static int SwigDirector_Driver_ProcessInternalMessages(Driver self, long resp_queue, long hdr, long data) {
    return self.ProcessInternalMessages(new QueuePointer(resp_queue, false), new player_msghdr_t(hdr, false), new SWIGTYPE_p_void(data, false));
  }
  public static boolean SwigDirector_Driver_RegisterProperty__SWIG_0(Driver self, String key, long prop, long cf, int section) {
    return self.RegisterProperty(key, new SWIGTYPE_p_Property(prop, false), new ConfigFile(cf, false), section);
  }
  public static boolean SwigDirector_Driver_RegisterProperty__SWIG_1(Driver self, long prop, long cf, int section) {
    return self.RegisterProperty(new SWIGTYPE_p_Property(prop, false), new ConfigFile(cf, false), section);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
