#!/usr/bin/python
import sys

Import('env')
env = env.Clone()

env.Prepend(CPPPATH = [ 
	'src', 
	'#ClientSML/src', 
	'#KernelSML/src',
	'#CommandLineInterface/src',
	'#SoarKernel/src',
	'#ElementXML/src',
	'#ConnectionSML/src',
	])

libadd = [ 'ClientSML', 'ConnectionSML', 'ElementXML' ]
if env['STATIC_LINKED']:
	libadd = [ 'ClientSML', 'ConnectionSML', 'ElementXML', 'SoarKernelSML', 'SoarKernel', 'CommandLineInterface', 'sqlite3' ]

if sys.platform == "darwin":
	if env['PLATFORM'] == '64':
		libadd.append('cppunit-osx-64')
	else:
		libadd.append('cppunit-osx')
else:
	if env['PLATFORM'] == '64':
		libadd.append('cppunit-linux-64')
	else:
		libadd.append('cppunit-linux')

libpath = [ '$PREFIX/lib', 'lib' ]

env.Append(LIBS = libadd, LIBPATH = libpath)
Tests = env.Program('Tests', Glob('src/*.cpp'))

env.Install('$PREFIX/bin', Tests)

# Install resources
env.InstallAs('$PREFIX/share/soar/Tests', '#Tests/Agents')
env.Clean(Tests, env.FindInstalledFiles())

