/* START OF AUTOGENERATED CODE */
/* This file or section was automatically generated by playerinterfacegen.py */

#include "example_interface.h"
#include "example_xdr.h"

// Function table for this interface
static playerxdr_function_t example_ftable[] =
{


  /* example messages */
  { PLAYER_EXAMPLE_CODE , PLAYER_MSGTYPE_DATA , PLAYER_EXAMPLE_DATA_EXAMPLE ,
    (player_pack_fn_t)player_eginterf_data_pack, (player_copy_fn_t)player_eginterf_data_t_copy, (player_cleanup_fn_t)player_eginterf_data_t_cleanup,(player_clone_fn_t)player_eginterf_data_t_clone,(player_free_fn_t)player_eginterf_data_t_free,(player_sizeof_fn_t)player_eginterf_data_t_sizeof},
  { PLAYER_EXAMPLE_CODE , PLAYER_MSGTYPE_REQ , PLAYER_EXAMPLE_REQ_EXAMPLE ,
    (player_pack_fn_t)player_eginterf_req_pack, (player_copy_fn_t)player_eginterf_req_t_copy, (player_cleanup_fn_t)player_eginterf_req_t_cleanup,(player_clone_fn_t)player_eginterf_req_t_clone,(player_free_fn_t)player_eginterf_req_t_free,(player_sizeof_fn_t)player_eginterf_req_t_sizeof},
  { PLAYER_EXAMPLE_CODE , PLAYER_MSGTYPE_CMD , PLAYER_EXAMPLE_CMD_EXAMPLE ,
    (player_pack_fn_t)player_eginterf_cmd_pack, (player_copy_fn_t)player_eginterf_cmd_t_copy, (player_cleanup_fn_t)player_eginterf_cmd_t_cleanup,(player_clone_fn_t)player_eginterf_cmd_t_clone,(player_free_fn_t)player_eginterf_cmd_t_free,(player_sizeof_fn_t)player_eginterf_cmd_t_sizeof},

  /* This NULL element signals the end of the list */
  {0,0,0,NULL,NULL,NULL}
};

playerxdr_function_t* player_plugininterf_gettable (void)
{
    return example_ftable;
}

/* END OF AUTOGENERATED CODE */
