#!/usr/bin/python
import glob
import shutil
import SoarSCons
import sys

Import('env')
env = env.Clone()

if sys.platform == 'cygwin':
    SoarSCons.SetJavaPaths(env, '"Core/ClientSMLSWIG/Java/sml.jar;SoarLibrary/bin/swt.jar"')
else:
    SoarSCons.SetJavaPaths(env, 'Core/ClientSMLSWIG/Java/sml.jar:SoarLibrary/bin/swt.jar')

env.Java(target = 'classes', source = 'src')

env.Append(JARCHDIR = 'Environments/JavaTOH/classes')
JavaTOH = env.Jar(target = 'JavaTOH.jar', source = ['classes', 'JarManifest', ])

env.Clean('classes', 'classes')
