#!/usr/bin/python

Import('env')
env = env.Clone()

env.Prepend(CPPPATH = ['src', '#ElementXML/src', '#ConnectionSML/src', ])

if env['SCU']:
	ClientSML = env.Library('ClientSML', 'ClientSML.cxx')
else:
	ClientSML = env.Library('ClientSML', Glob('src/*.cpp'))

env.Install('$PREFIX/lib', ClientSML)

# Install includes
env.Install('$PREFIX/include', Glob('src/*.h'))
env.Clean(ClientSML, env.FindInstalledFiles())

