#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#

Import('env')

PuddleWorld = env.Install('$OUT_DIR', env.Program('PuddleWorld', 'PuddleWorld.cpp'))
env.Alias('puddleworld', PuddleWorld + env.Install('$OUT_DIR/test_agents', 'puddle-world.soar'))
