#!/usr/bin/python
import glob
import sys

Import('env')
env = env.Clone()
env.Prepend(CPPPATH = [	'../../Core/ClientSML/include',
			'../../Core/ElementXML/include',
			'../../Core/ConnectionSML/include'])

libadd = [ 'ClientSML', 
	   'ConnectionSML',
	   'ElementXML', 
	   ]

if sys.platform == 'cygwin':
	libadd.extend(['ws2_32',])

libpath = [ '../../Core/ClientSML',
	    '../../Core/ConnectionSML',
	    '../../Core/ElementXML', 
	    ]
	   
env.Append(LIBS = libadd, LIBPATH = libpath)
TestCLI = env.Program('TestCLI', glob.glob('*.cpp'))
env.Install('#SoarLibrary/bin', TestCLI)
