/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class FloatElement extends WMElement {
  private long swigCPtr;

  protected FloatElement(long cPtr, boolean cMemoryOwn) {
    super(smlJNI.SWIGFloatElementUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FloatElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected FloatElement() {
    this(0, false);
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
    super.delete();
  }

  public String GetValueType() {
    return smlJNI.FloatElement_GetValueType(swigCPtr);
  }

  public String GetValueAsString() {
    return smlJNI.FloatElement_GetValueAsString(swigCPtr);
  }

  public double GetValue() {
    return smlJNI.FloatElement_GetValue(swigCPtr);
  }

  public FloatElement ConvertToFloatElement() {
    long cPtr = smlJNI.FloatElement_ConvertToFloatElement(swigCPtr);
    return (cPtr == 0) ? null : new FloatElement(cPtr, false);
  }

}
