/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.22
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class IntElement extends WMElement {
  private long swigCPtr;

  protected IntElement(long cPtr, boolean cMemoryOwn) {
    super(smlJNI.SWIGIntElementUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected IntElement() {
    this(0, false);
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
    super.delete();
  }

  public String GetValueType() {
    return smlJNI.IntElement_GetValueType(swigCPtr);
  }

  public String GetValueAsString() {
    return smlJNI.IntElement_GetValueAsString(swigCPtr);
  }

  public int GetValue() {
    return smlJNI.IntElement_GetValue(swigCPtr);
  }

  public IntElement ConvertToIntElement() {
    long cPtr = smlJNI.IntElement_ConvertToIntElement(swigCPtr);
    return (cPtr == 0) ? null : new IntElement(cPtr, false);
  }

}
