/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public final class smlAgentEventId {
  public final static smlAgentEventId smlEVENT_AFTER_AGENT_CREATED = new smlAgentEventId("smlEVENT_AFTER_AGENT_CREATED", smlProductionEventId.smlEVENT_BEFORE_PRODUCTION_RETRACTED.swigValue() + 1);
  public final static smlAgentEventId smlEVENT_BEFORE_AGENT_DESTROYED = new smlAgentEventId("smlEVENT_BEFORE_AGENT_DESTROYED");
  public final static smlAgentEventId smlEVENT_BEFORE_AGENTS_RUN_STEP = new smlAgentEventId("smlEVENT_BEFORE_AGENTS_RUN_STEP");
  public final static smlAgentEventId smlEVENT_BEFORE_AGENT_REINITIALIZED = new smlAgentEventId("smlEVENT_BEFORE_AGENT_REINITIALIZED");
  public final static smlAgentEventId smlEVENT_AFTER_AGENT_REINITIALIZED = new smlAgentEventId("smlEVENT_AFTER_AGENT_REINITIALIZED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static smlAgentEventId swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + smlAgentEventId.class + " with value " + swigValue);
  }

  private smlAgentEventId(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private smlAgentEventId(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private static smlAgentEventId[] swigValues = { smlEVENT_AFTER_AGENT_CREATED, smlEVENT_BEFORE_AGENT_DESTROYED, smlEVENT_BEFORE_AGENTS_RUN_STEP, smlEVENT_BEFORE_AGENT_REINITIALIZED, smlEVENT_AFTER_AGENT_REINITIALIZED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}


