/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.22
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public final class smlRhsEventId {
  public final static smlRhsEventId smlEVENT_RHS_USER_FUNCTION = new smlRhsEventId("smlEVENT_RHS_USER_FUNCTION", smlPrintEventId.smlEVENT_PRINT.swigValue() + 1);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static smlRhsEventId swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + smlRhsEventId.class + " with value " + swigValue);
  }

  private smlRhsEventId(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private smlRhsEventId(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private static smlRhsEventId[] swigValues = { smlEVENT_RHS_USER_FUNCTION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}


