/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public final class smlXMLEventId {
  public final static smlXMLEventId smlEVENT_XML_TRACE_OUTPUT = new smlXMLEventId("smlEVENT_XML_TRACE_OUTPUT", smlRhsEventId.smlEVENT_RHS_USER_FUNCTION.swigValue() + 1);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static smlXMLEventId swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + smlXMLEventId.class + " with value " + swigValue);
  }

  private smlXMLEventId(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private smlXMLEventId(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private static smlXMLEventId[] swigValues = { smlEVENT_XML_TRACE_OUTPUT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}


