/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class SWIGTYPE_p_ElementXML_InterfaceStructTag {
  private long swigCPtr;

  protected SWIGTYPE_p_ElementXML_InterfaceStructTag(long cPtr, boolean bFutureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_ElementXML_InterfaceStructTag() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_ElementXML_InterfaceStructTag obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

