#!/usr/bin/python
import glob

Import('env')
env = env.Copy()
env.Append(CPPFLAGS = ' -fno-strict-aliasing')
env.Prepend(CPPPATH = ['src', 'include', '../gSKI/include', '../CLI/include'])

SoarKernel = env.Library('SoarKernel', glob.glob('src/*.cpp'))
env.Install('#SoarLibrary/lib', SoarKernel)
