#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
Import('env')
TestSoarPerformance = env.Program('TestSoarPerformance', Glob('*.cpp'))
env.Alias('TestSoarPerformance', env.Install('$OUT_DIR', TestSoarPerformance))

