#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#

Import('compEnv')
env = compEnv.Clone()

TestSoarPerformance = env.Program('TestSoarPerformance', Glob('*.cpp'))
env.Install('$PREFIX/bin', TestSoarPerformance)

