#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
Import('compEnv')
TestSoarPerformance = compEnv.Program('TestSoarPerformance', Glob('*.cpp'))
compEnv.Install('$PREFIX/bin', TestSoarPerformance)

