#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
Import('env')

lib = env.SharedLibrary('TestExternalLibraryLib', 'lib.cpp')
prog = env.Program('TestExternalLibrary', 'TestExternalLibrary.cpp')
t = env.Install('$OUT_DIR', [prog, lib])
Return('t')
