#!/usr/bin/python

Import('env')
env = env.Clone()

env.Prepend(CPPPATH = ['src', 
		       'include', 
		       '#SoarKernel/include',
		       '#CLI/include',
		       '#ElementXML/include',
		       '#ConnectionSML/include'])

libadd = [
	   'ElementXML',
	   'CommandLineInterface',
	   'ConnectionSML',
	   'SoarKernel',
	   'sqlite3',
	   ]

if env['SCU']:
	SoarKernelSML = env.SharedLibrary('SoarKernelSML', 'KernelSML.cxx', LIBS = libadd, LIBPATH = '$PREFIX/lib')
else:
	SoarKernelSML = env.SharedLibrary('SoarKernelSML', Glob('src/*.cpp'), LIBS = libadd, LIBPATH = '$PREFIX/lib')

env.Install('$PREFIX/lib', SoarKernelSML)

