#!/bin/sh

pushd kernel
chmod u+x ./configure

./configure
if [ $? == "1" ]; then
  echo
  echo "*** Couldn't configure kernel (check for error messages above)."
  exit
fi

make
popd
pushd tcl-interface
chmod u+x ./configure

./configure --prefix=../.. --with-kernel=../kernel
if [ $? == "1" ]; then

  ./configure --prefix=../.. --with-tcl-lib-dir=/usr/local/ActiveTcl/lib \
  --with-tcl-doc-dir=/usr/local/ActiveTcl/man --with-tk-lib-dir=/usr/local/ActiveTcl/lib  \
  --with-kernel=../kernel
  if [ $? == "1" ]; then
    echo
    echo "*** Couldn't configure tcl-interface (check for error messages above)."
    exit
  fi
fi

make
cp  libsoar8.5* ../library
popd
