#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
import sys

Import('env')
clone = env.Clone()

libadd = ['Soar']

if sys.platform == "darwin":
	if GetOption('platform') == '64':
		libadd.append('cppunit-osx-64')
	else:
		libadd.append('cppunit-osx')
else:
	if GetOption('platform') == '64':
		libadd.append('cppunit-linux-64')
	else:
		libadd.append('cppunit-linux')

clone.Prepend(LIBS = libadd, LIBPATH = ['lib'], CPPPATH = env.Dir('src').srcnode())
t = env.Install('$OUT_DIR', clone.Program('UnitTests', Glob('src/*.cpp')))
Return('t')
