# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: ilammy/msvc-dev-cmd@v1
      
      # install dependencies
      # refresh env vars so can find tcl on the path
      # find tclsh, which will be in something like c:\<tcllocation>\bin\tclsh.exe
      # get the parent parent directory to get c:\<tcllocation>, and create a symlink to make that
      # appear at c:\Tcl, which is where the scons script expects it on windows
      - name: Install requirements
        run: |
            choco install magicsplat-tcl-tk --no-progress
            choco install swig --no-progress
            refreshenv
            $tclPath = split-path (split-path (get-command tclsh).Path)
            cmd /c mklink /d c:\Tcl $tclPath
      - name: Build everything
        run: ./build.bat all
      - name: Run tests 
        run: |
          cd out
          ./UnitTests
