#!/usr/bin/python
import glob

Import('env')
env = env.Clone()
env.Prepend(CPPPATH = ['src', 'include', '../ElementXML/include', '../ConnectionSML/include', ])

if env['scu']:
	ClientSML = env.Library('ClientSML', 'ClientSML.cxx')
else:
	ClientSML = env.Library('ClientSML', glob.glob('src/*.cpp'))
env.Install('#SoarLibrary/lib', ClientSML)
